import { studentService } from '@/services/studentService';

// Department mapping based on course codes
const getDepartmentFromCourse = (course: string): string => {
  const courseUpper = course.toUpperCase();
  
  // CECE (College of Engineering and Civil Engineering)
  if (['BSCE', 'BSEE', 'BSECE', 'BSECE', 'BSME', 'BSCHE', 'BSIE', 'BSCPE'].includes(courseUpper)) {
    return 'CECE';
  }
  
  // CBA (College of Business Administration)
  if (['BSBA', 'BSA', 'BSMA', 'BSCA', 'BSE'].includes(courseUpper)) {
    return 'CBA';
  }
  
  // CTELAN (College of Technology, Education, Liberal Arts, and Nursing)
  // This includes IT, Education, Liberal Arts, Nursing, etc.
  return 'CTELAN';
};

export const bulkImportStudents2025 = async () => {
  const students = [
    { id: '2025-019', name: 'BAJENTING, KRISTEL JIEZAN ESTACIONES', course: 'BSEd', year: '1st Year' },
    { id: '2025-326', name: 'BALBUENA, KHEAN', course: 'BS Psychology', year: '1st Year' },
    { id: '2024-347', name: 'BALICO, CLYDE MAUEL PAMAN', course: 'BSA', year: '1st Year' },
    { id: '2025-010', name: 'BANDOY, KRISTINE TAOY', course: 'BSN', year: '1st Year' },
    { id: '2025-009', name: 'BANDOY, MEISHEE SHEIN', course: 'BA PoS', year: '1st Year' },
    { id: '2025-278', name: 'BANGERO, AEIRON JAMES LEGORIO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-004', name: 'BANGOT, KURT ANGELO DELA CRUZ', course: 'BSN', year: '1st Year' },
    { id: '2025-097', name: 'BANSIL, NORJANNAH SALIC', course: 'BSA', year: '1st Year' },
    { id: '2025-232', name: 'BANSILAN, ARYAN FERDAUZ MAMASABULOD', course: 'BSCE', year: '1st Year' },
    { id: '2025-334', name: 'BANZON, ROLLY JOROLAN', course: 'PROF ED', year: '1st Year' },
    { id: '2025-012', name: 'BAROT, LIANE', course: 'BS Psychology', year: '1st Year' },
    { id: '2024-346', name: 'BARRETE, JAMES LLOYD CABILOGAN', course: 'BSBA', year: '1st Year' },
    { id: '2025-145', name: 'BARRIENTOS, JYRHA KYLE ALEJANDRO', course: 'BSA', year: '1st Year' },
    { id: '2025-011', name: 'BATAL, CHRISTOPHER BRENT LOQUINTE', course: 'BSA', year: '1st Year' },
    { id: '2025-072', name: 'BAUTISTA, VEA PAGAYAO', course: 'BSEd', year: '1st Year' },
    { id: '2025-124', name: 'BAYAO, JURIE PLANG', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-036', name: 'BAYAO, JUSTIN CAUMPONGAN', course: 'BSN', year: '1st Year' },
    { id: '2025-109', name: 'BAYAWAN, JENS BENEDICT SILLADOR', course: 'BSCE', year: '1st Year' },
    { id: '2025-289', name: 'BAYAWAN, PEJAY LUMAYON', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-280', name: 'BEDICO, JERICHO TUNGCALING', course: 'BSMA', year: '1st Year' },
    { id: '2025-139', name: 'BELARMINO, ELIZA KATE PAGUICAN', course: 'BSMA', year: '1st Year' },
    { id: '2025-263', name: 'BELONIO, RUTCHIE CAPISTRANO', course: 'BSIT', year: '1st Year' },
    { id: '2025-233', name: 'BENDO, JOHN MAVERICK JAMON', course: 'BSIT', year: '1st Year' },
    { id: '2025-314', name: 'BERAME, IVAN ANDREW ESCURO', course: 'BSIT', year: '1st Year' },
    { id: '2025-157', name: 'BERANGEL, JOSHUA REBUSIT', course: 'BSCE', year: '1st Year' },
    { id: '2025-180', name: 'BERMUDO, ZIA KEITH PADASAS', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-277', name: 'BERNALDEZ, RYZA ANNABELLE PINAPIT', course: 'PROF ED', year: '1st Year' },
    { id: '2025-205', name: 'BERZAMINA, MARK ZEMRIO QUIJANO', course: 'BSCE', year: '1st Year' },
    { id: '2025-197', name: 'BIACA, JONATHAN GUMBAN', course: 'PROF ED', year: '1st Year' },
    { id: '2025-158', name: 'BIEREN, CHARMIEL JAINAR', course: 'BSCE', year: '1st Year' },
    { id: '2025-093', name: 'BOLIVAR, ABE JILL BUNDA', course: 'BSN', year: '1st Year' },
    { id: '2025-319', name: 'BONILLA, TIMOTHY JOSEPH BANAC', course: 'BSIT', year: '1st Year' },
    { id: '2025-333', name: 'BORJA, ALEXA PEARL BLAYA', course: 'BA PoS', year: '1st Year' },
    { id: '2025-200', name: 'BORRES, ROSE HERBOLINGO', course: 'PROF ED', year: '1st Year' },
    { id: '2025-234', name: 'BRITOS, CHLOE TAMONAN', course: 'BSBA', year: '1st Year' },
    { id: '2025-300', name: 'BUNED, RENA JEAN SASANA', course: 'BSBA', year: '1st Year' },
    { id: '2025-306', name: 'BUNIEL, BEN JOSEPH DONGUINES', course: 'BSEd', year: '1st Year' },
    { id: '2025-183', name: 'CABAGNOT, KARL JAMES CARCILLAR', course: 'BPEd', year: '1st Year' },
    { id: '2025-001', name: 'CABANAYAN, NADINE MIÑAO', course: 'PROF ED', year: '1st Year' },
    { id: '2025-058', name: 'CABANGAL, JOHN VINCENT CABILA', course: 'BA Philo', year: '1st Year' },
    { id: '2025-088', name: 'CABILAO, SHYNA AMOR DAPITO', course: 'BSCE', year: '1st Year' },
    { id: '2025-102', name: 'CABILO, JAMAICA KABAGANI', course: 'BSEd', year: '1st Year' },
    { id: '2025-086', name: 'CABILO, NARISSA KABAGANI', course: 'BSCE', year: '1st Year' },
    { id: '2025-225', name: 'CABURATAN, KISSEAH VYNE CAÑADILLA', course: 'BSCE', year: '1st Year' },
    { id: '2025-060', name: 'CACHUELA, LIZTER JAMES DAGOOC', course: 'BA Philo', year: '1st Year' },
    { id: '2025-182', name: 'CADABONA, AVREN', course: 'BA PoS', year: '1st Year' },
    { id: '2025-231', name: 'CADIZ, RAINER JOSH LUGATIMAN', course: 'BPEd', year: '1st Year' },
    { id: '2025-025', name: 'CALIXTRO, IVAN RITCHIE CRASQUIT', course: 'BA PoS', year: '1st Year' },
    { id: '2025-321', name: 'CALLAMAN, JHONA MEA GILAGA', course: 'BSBA', year: '1st Year' },
    { id: '2025-345', name: 'CAMPO, ALLIYAH JANE DAGOL', course: 'BSN', year: '1st Year' },
    { id: '2025-189', name: 'CAMPOMANES, LAWRENZE ANDREW AJERO', course: 'BA PoS', year: '1st Year' },
    { id: '2025-174', name: 'CANDA, SEAN PRAXIS SOCIAS', course: 'BSIT', year: '1st Year' },
    { id: '2025-210', name: 'CANDELARIO, HANNAH DOROTHY PEDROSO', course: 'BSCE', year: '1st Year' },
    { id: '2025-041', name: 'CANTARONA, CEASAR JOHN JORE', course: 'PROF ED', year: '1st Year' },
    { id: '2025-260', name: 'CARI, JOHN MENARD PADILLA', course: 'BSEcE', year: '1st Year' },
    { id: '2025-131', name: 'CASIMERO, MARYVON NICOLE PIDO', course: 'BSBA', year: '1st Year' },
    { id: '2025-152', name: 'CASINILLO, SHAIRA MAE DALIDA', course: 'BPEd', year: '1st Year' },
    { id: '2025-020', name: 'CASPILLO, RAECEE KEAH SIMBRON', course: 'BSN', year: '1st Year' },
    { id: '2025-365', name: 'CASTILLO, JOHN BERNARD PEÑARANDA', course: 'PROF ED', year: '1st Year' },
    { id: '2025-290', name: 'CATALUÑA, JORELLS JEPH ESPARAGOZA', course: 'BSIT', year: '1st Year' },
    { id: '2025-192', name: 'CATERIO, CYRIL JAY ESPINOSA', course: 'BSEcE', year: '1st Year' },
    { id: '2025-128', name: 'CEDEÑO, JAMELA JOY QUINANAHAN', course: 'BSN', year: '1st Year' },
    { id: '2025-031', name: 'CELORIO, ROMELISA PALMA', course: 'BSEd', year: '1st Year' },
    { id: '2025-026', name: 'CERCADO, KRISTAL JOY SALVALOZA', course: 'BSCE', year: '1st Year' },
    { id: '2025-164', name: 'CLAUD, PRINCE JAY-LON FRANCISCO', course: 'BSBA', year: '1st Year' },
    { id: '2025-043', name: 'CLAVERIA, BENHART KIBANGAN', course: 'BSBA', year: '1st Year' },
    { id: '2024-022', name: 'COLLANTES, KIM JOHN ALVAREZ', course: 'BSN', year: '1st Year' },
    { id: '2024-229', name: 'COMODA, CLAIRE ORTIZ', course: 'BSBA', year: '1st Year' },
    { id: '2025-016', name: 'CONTINEDO, PRINCE JOHN CARL CASINAO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-044', name: 'CORDOVA, HYACINTH CARAGOS', course: 'BPEd', year: '1st Year' },
    { id: '2025-054', name: 'CORPUZ, KYLE ANGELA GEOLINGO', course: 'BSN', year: '1st Year' },
    { id: '2025-002', name: 'CUMAYAS, CHRISTIAN REY DELA CERNA', course: 'BSIT', year: '1st Year' },
    { id: '2025-029', name: 'CUTAD, PRINCES CLAIRE GONZAGA', course: 'BSA', year: '1st Year' },
    { id: '2025-187', name: 'DABUCO, JULS ERICK PERONCE', course: 'BSMA', year: '1st Year' },
    { id: '2025-251', name: 'DACUMOS, JALILA CREST PEPITO', course: 'BSN', year: '1st Year' },
    { id: '2025-279', name: 'DAGUMAN, JOSELE KRIS TANGARA', course: 'BSBA', year: '1st Year' },
    { id: '2025-057', name: 'DAJUELA, RONALD PILLO', course: 'BA Philo', year: '1st Year' },
    { id: '2025-310', name: 'DALUGDOG, ANA MARIE GALVE', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-045', name: 'DANDUAN, CHARLY ANGELES', course: 'BSBA', year: '1st Year' },
    { id: '2025-085', name: 'DANGO, MARICEL BROÑULA', course: 'BSBA', year: '1st Year' },
    { id: '2025-091', name: 'DANO, AECEY CEBALLOS', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-120', name: 'DAQUIPIL, SHERLYN OBTINALLA', course: 'BSA', year: '1st Year' },
    { id: '2025-138', name: 'DAUGDAUG, CHARMEN DUHILAG', course: 'BPEd', year: '1st Year' },
    { id: '2025-046', name: 'DAYONDON, COLLEEN BORGONIA', course: 'BPEd', year: '1st Year' },
    { id: '2025-017', name: 'DAYONDON, PRECIOUS DIANNE DELPOSO', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-087', name: 'DE VIEJO, MARISSA PUROL', course: 'BSBA', year: '1st Year' },
    { id: '2025-336', name: 'DECLARADOR, JANA LEIGHN DAFIELMOTO', course: 'BSN', year: '1st Year' },
    { id: '2025-136', name: 'DEGUIÑON, AXINE ARL HEAVEN BATUCAN', course: 'BPEd', year: '1st Year' },
    { id: '2025-032', name: 'DEL MUNDO, JENYVEB AMENA', course: 'BSBA', year: '1st Year' },
    { id: '2025-039', name: 'DELA CRUZ, ERNEL SUAREZ', course: 'PROF ED', year: '1st Year' },
    { id: '2025-118', name: 'DELA CRUZ, GEORGE GABRIEL DIMAANO', course: 'BSN', year: '1st Year' },
    { id: '2025-144', name: 'DELA CUESTA, KEITH CHRISLER CHATTO', course: 'BPEd', year: '1st Year' },
    { id: '2025-216', name: 'DELFIN, BIANCA JOLYN TION', course: 'BSCE', year: '1st Year' },
    { id: '2021-389', name: 'DELIMA, RIZZA MAE ROLA', course: 'BA Comm', year: '1st Year' },
    { id: '2025-221', name: 'DELINO, JOHN TERRENCE ZAMBRA', course: 'BSBA', year: '1st Year' },
    { id: '2025-322', name: 'DELOS REYES, HANNAH JULIAN SEVILA', course: 'BSBA', year: '1st Year' },
    { id: '2025-298', name: 'DICDIQUIN, LENY NIM', course: 'BSMA', year: '1st Year' },
    { id: '2025-024', name: 'DIEZ, KATHERINE OMANDAC', course: 'BSCE', year: '1st Year' },
    { id: '2025-285', name: 'DIMAANO, DAN JENSEN RAMIREZ', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-166', name: 'DIVINAGRACIA, LEZYLLE MAE DONASCO', course: 'BSA', year: '1st Year' },
    { id: '2025-006', name: 'DOCTOR, ANIKA LORAINE SOLEDAD', course: 'BSMA', year: '1st Year' },
    { id: '2025-034', name: 'DOMINGO, LADY JANE WAGAS', course: 'BSA', year: '1st Year' },
    { id: '2025-282', name: 'DORILAG, ASHTON ALFARAS', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-259', name: 'DOYO, KEITH BYRON FABELLO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-350', name: 'DULAY, BON PATRICK SAPUL', course: 'BSCE', year: '1st Year' },
    { id: '2025-347', name: 'EDRIS, AINOLHAYA SULTAN', course: 'BSN', year: '1st Year' },
    { id: '2025-295', name: 'EDUAVE, JOSHUA CADENAS', course: 'BEEd', year: '1st Year' },
    { id: '2025-073', name: 'ESCALANTE, GEHANNAH ROSE MAULANA', course: 'BSIT', year: '1st Year' },
    { id: '2025-270', name: 'ESCOPALAO, KESHIA ESPAÑOLA', course: 'BSBA', year: '1st Year' },
    { id: '2025-042', name: 'ESPINOSA, LADY JESSICA DEMERIN', course: 'BSIT', year: '1st Year' },
    { id: '2025-364', name: 'ESTRERA, KHIZZ DIANE BANDIOLA', course: 'PROF ED', year: '1st Year' },
    { id: '2025-104', name: 'EXCONDE, AYANNA AXEL BRAGAIS', course: 'BSMA', year: '1st Year' },
    { id: '2025-264', name: 'FABRO, JAIRUS MARCELINO', course: 'BSIT', year: '1st Year' },
    { id: '2025-127', name: 'FALCIS, ASHLEY RESMA', course: 'BSCE', year: '1st Year' },
    { id: '2025-213', name: 'FAMISAN, NATHANIEL ASIS', course: 'PROF ED', year: '1st Year' },
    { id: '2025-077', name: 'FERENAL, JOSHUA BARSAGA', course: 'BSBA', year: '1st Year' },
    { id: '2025-313', name: 'FERNANDEZ, KIRK LOUIE CARAS', course: 'BSEcE', year: '1st Year' },
    { id: '2025-297', name: 'FERRER, JOHN RICK SANGILAN', course: 'BSA', year: '1st Year' },
    { id: '2025-296', name: 'FIGUEROA, KRISTINE MAY MIZON', course: 'BA PoS', year: '1st Year' },
    { id: '2025-149', name: 'FLORES, PRECIOUS JEAMELLA EVANGELISTA', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-309', name: 'FLORITA, JACIENTH CLAIRE PERFAS', course: 'BSMA', year: '1st Year' },
    { id: '2025-083', name: 'FORTUNA, GIAN CARLO DELPOSO', course: 'BSBA', year: '1st Year' },
    { id: '2025-292', name: 'FORTUNA, JENNY ROSE DELPOSO', course: 'BPEd', year: '1st Year' },
    { id: '2025-082', name: 'FRANCO, FEL LYZA NAMOCATCAT', course: 'BSA', year: '1st Year' },
    { id: '2025-108', name: 'GAJES, JANIEL SAMILLANO', course: 'BSCE', year: '1st Year' },
    { id: '2025-330', name: 'GALIZA, REA JANE PANES', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-262', name: 'GANIA, CARLO DANTE SAMAL', course: 'BSCE', year: '1st Year' },
    { id: '2025-134', name: 'GARCIA, XAMUEL XYREN REI CORPUZ', course: 'BA PoS', year: '1st Year' },
    { id: '2025-159', name: 'GAURAN, ANDREY ORIGEN', course: 'BA Philo', year: '1st Year' },
    { id: '2025-349', name: 'GIDO, ALYSSA CLAIRE SINCERO', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-049', name: 'GILACAN, JARL M ARNOLD JIMENA', course: 'BSN', year: '1st Year' },
    { id: '2025-176', name: 'GILBERO, JULIE PEARL PAQUIT', course: 'BSBA', year: '1st Year' },
    { id: '2025-170', name: 'GISON, PIONAH ELLAINE VILLEGAS', course: 'BSCE', year: '1st Year' },
    { id: '2025-114', name: 'GO, MIKEL JEFF BAYLON', course: 'BSCE', year: '1st Year' },
    { id: '2025-033', name: 'GOMEZ, LEO ANTHONY LOCARIO', course: 'BSCE', year: '1st Year' },
    { id: '2025-348', name: 'GRACIA, JANE JELIE DAPAL', course: 'PROF ED', year: '1st Year' },
    { id: '2025-291', name: 'GREGORIO, ALEXA VELARDE', course: 'BSA', year: '1st Year' },
    { id: '2025-198', name: 'GRIÑO, WINSTON YLMAR TAMAYOR', course: 'PROF ED', year: '1st Year' },
    { id: '2025-132', name: 'GUBAT, JUN VINCENT TUMBALOY', course: 'BA Comm', year: '1st Year' },
    { id: '2025-316', name: 'GUBATON, JERIAN SARINO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-248', name: 'GUCOR, BRIAN JAMES TABILO', course: 'BSIT', year: '1st Year' },
    { id: '2025-148', name: 'GUEVARRA, JOIE ELLAINE GAPUZ', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-095', name: 'HADJI RACMAN, HANIMA DIMA', course: 'BSN', year: '1st Year' },
    { id: '2025-244', name: 'HERIDA, SYRELL BARAWIDAN', course: 'BSIT', year: '1st Year' },
    { id: '2025-168', name: 'HERNAN, MARY CHIARA EXCHAURE', course: 'BSBA', year: '1st Year' },
    { id: '2025-340', name: 'HERNANDEZ, NOLYRAINE KRYZEL CAMPAÑA', course: 'BSA', year: '1st Year' },
    { id: '2025-362', name: 'HEYRES, JAMAICA MAE ARCENAL', course: 'BSCE', year: '1st Year' },
    { id: '2025-303', name: 'HORDISTA, MARIA FE SABAS', course: 'BSBA', year: '1st Year' },
    { id: '2025-337', name: 'INECIAL, ANGEL FAITH CENCIA', course: 'BA PoS', year: '1st Year' },
    { id: '2025-332', name: 'INECIAL, CHRISTIAN DOMINIC CENCIA', course: 'BSCE', year: '1st Year' },
    { id: '2025-265', name: 'JAMIL, MOJAINOR DIMAPORO', course: 'BSCE', year: '1st Year' },
    { id: '2025-344', name: 'JORIDICO, JAHN ALBERT TE', course: 'BSCE', year: '1st Year' },
    { id: '2025-155', name: 'JUMAO-AS, ALLYSSA KRIZETTE PALCA', course: 'BSA', year: '1st Year' },
    { id: '2025-172', name: 'JUNTARCIEGO, ANGELA TRESHA LAUREN', course: 'BSBA', year: '1st Year' },
    { id: '2025-171', name: 'JURIAL, PHOEBE JOY ARISTON', course: 'BSA', year: '1st Year' },
    { id: '2025-240', name: 'KINGCO, FRANCIS JADE COYOCA', course: 'BA PoS', year: '1st Year' },
    { id: '2025-130', name: 'LABONETE, THRIXIA BRIANNE JEEZE BALDEMORO', course: 'BSCE', year: '1st Year' },
    { id: '2025-266', name: 'LAMAY, MARIA TRISHA VALERIE DECASA', course: 'BSN', year: '1st Year' },
    { id: '2025-311', name: 'LAMPAYAN, NICOLE JULLIEZA', course: 'BSBA', year: '1st Year' },
    { id: '2025-188', name: 'LANGOMES, CHRISTIAN LIBRE', course: 'BA PoS', year: '1st Year' },
    { id: '2025-048', name: 'LAPUZ, DEEANNE RYZEL PARCON', course: 'BSN', year: '1st Year' },
    { id: '2025-267', name: 'LATO, SHANIAH ROSE MAE ARCIPE', course: 'BSN', year: '1st Year' },
    { id: '2025-201', name: 'LAURON, GEZER KENT TAN', course: 'PROF ED', year: '1st Year' },
    { id: '2025-023', name: 'LIBLORA, OLYN CASPILLO', course: 'BSCE', year: '1st Year' },
    { id: '2024-258', name: 'LIMA, LOIDJIE CELESTIAL', course: 'BSBA', year: '1st Year' },
    { id: '2025-067', name: 'LOSIS, ADRIAN JOHN APURADO', course: 'BSN', year: '1st Year' },
    { id: '2025-037', name: 'LUCERO, DION CLAYTON EBARLE', course: 'BSBA', year: '1st Year' },
    { id: '2025-249', name: 'LUMACAD, GLAIZA PHIERL MARTINEZ', course: 'BSIT', year: '1st Year' },
    { id: '2025-339', name: 'LUMOGDANG, LHEA LANITON', course: 'BSA', year: '1st Year' },
    { id: '2024-215', name: 'LUZON, KIEFER ERIC C', course: 'BSBA', year: '1st Year' },
    { id: '2025-115', name: 'MADIAM, ALEXA SERVANO', course: 'BSA', year: '1st Year' },
    { id: '2025-217', name: 'MAGCALAYO, FELIX DANIEL DURAN', course: 'BSIT', year: '1st Year' },
    { id: '2025-308', name: 'MAGDATO, JOHN KEVIN', course: 'BPEd', year: '1st Year' },
    { id: '2025-273', name: 'MALINGCO, HAYDEE KRISNA SAMAL', course: 'BSCE', year: '1st Year' },
    { id: '2025-324', name: 'MAMAYOG, NYSRHEEN CASULOCAN', course: 'BSA', year: '1st Year' },
    { id: '2025-147', name: 'MAMBURAO, JEAMEL HEART OBAÑA', course: 'BSN', year: '1st Year' },
    { id: '2025-352', name: 'MAMON, VONN KLYDE PUSTA', course: 'PROF ED', year: '1st Year' },
    { id: '2025-268', name: 'MANANSALA, ALLYSSON ANABIEZA', course: 'BSEd', year: '1st Year' },
    { id: '2025-287', name: 'MANLUNAS, NOAH JAY ELTAGON', course: 'BSEcE', year: '1st Year' },
    { id: '2025-224', name: 'MANTULING, NASRAH PENDATUN', course: 'BSBA', year: '1st Year' },
    { id: '2025-356', name: 'MAPA, JUDE MICHAEL MAINIT', course: 'BSCE', year: '1st Year' },
    { id: '2025-190', name: 'MAPANAO, VINCE YUAN COLLADO', course: 'BSCE', year: '1st Year' },
    { id: '2025-084', name: 'MAPUTI, KIEZAH GAIL GLIMADA', course: 'BSBA', year: '1st Year' },
    { id: '2025-359', name: 'MARAGANA, JUSTIN PHILIP NOBLE', course: 'PROF ED', year: '1st Year' },
    { id: '2025-191', name: 'MARFE, JETRO JADE SOBREO', course: 'BPEd', year: '1st Year' },
    { id: '2025-092', name: 'MARQUEZ, GREMAN JANOFER LAPAZ', course: 'BSIT', year: '1st Year' },
    { id: '2025-286', name: 'MEJORADA, JOHN REVO AHIT', course: 'BSIT', year: '1st Year' },
    { id: '2025-293', name: 'MEJORADA, MARK RAVEN AHIT', course: 'BSBA', year: '1st Year' },
    { id: '2025-179', name: 'MENDEZ, REIL ANTHONY ANJAO', course: 'BSIT', year: '1st Year' },
    { id: '2025-253', name: 'MENDOZA, JOHN DOMINIC LEGASPI', course: 'BSN', year: '1st Year' },
    { id: '2025-366', name: 'MENTANG, ALMIRA ANGKAD', course: 'PROF ED', year: '1st Year' },
    { id: '2025-089', name: 'MERIN, LE JOSIAS MADRIO', course: 'BSCE', year: '1st Year' },
    { id: '2024-367', name: 'MILLOMEDA, JOHN LESTER RENDAJE', course: 'BSCE', year: '1st Year' },
    { id: '2025-294', name: 'MOJER, DAEVONE CAMPANO', course: 'BSBA', year: '1st Year' },
    { id: '2025-137', name: 'MONSERATE, NIÑA CHARISSE CUBERO', course: 'BSA', year: '1st Year' },
    { id: '2025-135', name: 'MONTECILLO, ANJELYN DELIMA', course: 'BSA', year: '1st Year' },
    { id: '2025-272', name: 'MONTERO, PRECIOUS KEYANN AARON', course: 'BSBA', year: '1st Year' },
    { id: '2025-254', name: 'MONTEROSO, WELTHON GIEM SALANDANAN', course: 'BSN', year: '1st Year' },
    { id: '2025-047', name: 'MORAN, ARVIN JOY CALUNOD', course: 'BSA', year: '1st Year' },
    { id: '2025-327', name: 'MORANTA, WINZEL LOUISSE GABRIELL RIBUYAS', course: 'BSA', year: '1st Year' },
    { id: '2025-367', name: 'MULAT, RAIZA MIRAFUENTES', course: 'PROF ED', year: '1st Year' },
    { id: '2025-030', name: 'MUSTAPHA, JEOMAR ALIUDIN', course: 'BPEd', year: '1st Year' },
    { id: '2025-110', name: 'NADNADEN, CARL JOSHUA JANOYAN', course: 'BSCE', year: '1st Year' },
    { id: '2025-133', name: 'NADONG, IAN FEL ALOY', course: 'BSCE', year: '1st Year' },
    { id: '2025-269', name: 'NAMIA, ALYAHNNA CZARRHYNE MANSUELO', course: 'BSBA', year: '1st Year' },
    { id: '2025-146', name: 'NAPUTO, ROMEO EDEJER', course: 'BPEd', year: '1st Year' },
    { id: '2025-177', name: 'NARCISO, NICOMEO REGIS', course: 'BSEd', year: '1st Year' },
    { id: '2025-329', name: 'NGAMOY, RAZHI SHANE BARRIENTOS', course: 'BSCE', year: '1st Year' },
    { id: '2025-169', name: 'NICOLAS, PRECIOUS FAITH LOPEZ', course: 'BSA', year: '1st Year' },
    { id: '2024-365', name: 'NOLAN, BRENT KELLY ABELLANOSA', course: 'BSIT', year: '1st Year' },
    { id: '2025-003', name: 'OBEÑA, ENRICK JACINTO', course: 'PROF ED', year: '1st Year' },
    { id: '2025-112', name: 'OCTAVIO, BEA CAMBEL', course: 'BSEd', year: '1st Year' },
    { id: '2025-163', name: 'OLIVEROS, CARL VINCENT JUMAWID', course: 'BSCE', year: '1st Year' },
    { id: '2024-044', name: 'OMANDAC, BETHSHEVA COLOMER', course: 'BEEd', year: '1st Year' },
    { id: '2025-162', name: 'OMANDAM, KERR KLOYD ZEDRIC ROCOLAN', course: 'BSIT', year: '1st Year' },
    { id: '2025-069', name: 'OMBROSA, MICHELLE LYN PACOT', course: 'BSBA', year: '1st Year' },
    { id: '2025-121', name: 'OPENDO, ANDREA MAE CADUNGON', course: 'BSA', year: '1st Year' },
    { id: '2025-119', name: 'ORBE, JANNA NICOLE AMERILA', course: 'BSN', year: '1st Year' },
    { id: '2025-126', name: 'OREGILA, AZALEAH MONTALVA', course: 'BSN', year: '1st Year' },
    { id: '2025-116', name: 'OREIRO, AJELENE BALOS', course: 'BSCE', year: '1st Year' },
    { id: '2025-178', name: 'OTON, ERRON KENT V.J CATALAN', course: 'BSIT', year: '1st Year' },
    { id: '2025-223', name: 'PACETE, MA. EDDESSA RAMOS', course: 'BSN', year: '1st Year' },
    { id: '2025-202', name: 'PADAWAN, JUNIEL QUIM HINAYON', course: 'BSCE', year: '1st Year' },
    { id: '2025-103', name: 'PALERMO, CYRIL KAYE VIDAD', course: 'BSBA', year: '1st Year' },
    { id: '2025-028', name: 'PALIJADO, JOHN ROWIN', course: 'BSCE', year: '1st Year' },
    { id: '2025-014', name: 'PANDIA, ALLYAN NAVARRO', course: 'BSCE', year: '1st Year' },
    { id: '2025-141', name: 'PANDONG, MERRY CHRIST MANTAWIL', course: 'PROF ED', year: '1st Year' },
    { id: '2025-094', name: 'PAPASIN, LEIGHANN DIEZON', course: 'BSN', year: '1st Year' },
    { id: '2025-099', name: 'PARDILLO, JOCEL PELORIANA', course: 'BSA', year: '1st Year' },
    { id: '2025-107', name: 'PAREÑAS, LORRAINE SARTE', course: 'BSN', year: '1st Year' },
    { id: '2025-175', name: 'PASTORIL, CHARLES BENEDICT TUMANGGONG', course: 'BSCE', year: '1st Year' },
    { id: '2025-027', name: 'PATAC, GARY ABO-ABO', course: 'BSIT', year: '1st Year' },
    { id: '2025-304', name: 'PATCHES, IVY FAYE MAGALLON', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-335', name: 'PENIERO, NATHAN ANIÑON', course: 'BSIT', year: '1st Year' },
    { id: '2025-195', name: 'PERAL, JOHN MARK DEVALID', course: 'PROF ED', year: '1st Year' },
    { id: '2025-325', name: 'PEREYRA, LAURENCE RAMOS', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-204', name: 'PILAPIL, CARL ANDRY BAYA', course: 'BSIT', year: '1st Year' },
    { id: '2025-129', name: 'POLICAR, EDRIAN PERALES', course: 'BSCE', year: '1st Year' },
    { id: '2025-105', name: 'POLINIO, ALMA JANE AGUILAR', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-066', name: 'PORRAS, PAULO EDRIAN CALANDRIA', course: 'BA Philo', year: '1st Year' },
    { id: '2025-070', name: 'PRE, PRINCE ZIELO VERDAN', course: 'BSCE', year: '1st Year' },
    { id: '2025-100', name: 'PUN-AN, JOHN CHRISTIAN TRANCE', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-255', name: 'QUANICO, RONALEN JUAREZ', course: 'BSMA', year: '1st Year' },
    { id: '2025-062', name: 'QUIMCO, KRISTOFFER ESTELLOSO', course: 'BSCE', year: '1st Year' },
    { id: '2024-078', name: 'QUIÑONES, MARIO IV NARCISO', course: 'BSCE', year: '1st Year' },
    { id: '2025-209', name: 'QUIROZ, JAMES JOHN PAUL CANDOLE', course: 'BSCE', year: '1st Year' },
    { id: '2025-302', name: 'RABUYA, CLOUIE TORREON', course: 'BSA', year: '1st Year' },
    { id: '2025-096', name: 'RAHMAN, JOHANIS BERNADAS', course: 'BSIT', year: '1st Year' },
    { id: '2025-237', name: 'RASUL, SITTIE AIMAH SUNGGOD', course: 'BSA', year: '1st Year' },
    { id: '2025-361', name: 'RAYMUNDO, LOVELYN JEAN PACIENTE', course: 'PROF ED', year: '1st Year' },
    { id: '2025-222', name: 'RAZON, THEO ALCONERA', course: 'BSIT', year: '1st Year' },
    { id: '2025-068', name: 'REGUYAL, DANIELLA MAE OCON', course: 'BSBA', year: '1st Year' },
    { id: '2025-355', name: 'RENEGADO, DOVE QUIBEDO', course: 'BSBA', year: '1st Year' },
    { id: '2025-052', name: 'RETIZA, JIRAH JOY LUMOGDANG', course: 'BA Comm', year: '1st Year' },
    { id: '2025-212', name: 'REYES, MAURICE RATILLA', course: 'BPEd', year: '1st Year' },
    { id: '2025-242', name: 'RICALE, PRINCESS CHAREZ PALOMO', course: 'BSA', year: '1st Year' },
    { id: '2025-228', name: 'RIVERA, JUSTINE LLOYD PATRICIO', course: 'BPEd', year: '1st Year' },
    { id: '2025-165', name: 'ROCHE, ADRIAN CARL UNTAL', course: 'BSCE', year: '1st Year' },
    { id: '2025-230', name: 'RONDAEL, TRESHA NICA SURIAGA', course: 'BSEd', year: '1st Year' },
    { id: '2024-353', name: 'ROSARIO, ANGELIKA KATE VERGARA', course: 'BSBA', year: '1st Year' },
    { id: '2025-079', name: 'SACASAN, KYLE CIAN PASCO', course: 'BSA', year: '1st Year' },
    { id: '2025-038', name: 'SAGAYCA, DWYNE MATHEW PEROCHO', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-219', name: 'SALAZAR, CHRISTIAN JOSH ABELLANA', course: 'BSIT', year: '1st Year' },
    { id: '2025-008', name: 'SALGADO, JOHNVER KENT DE VILLA', course: 'BSMA', year: '1st Year' },
    { id: '2025-214', name: 'SALIK, SHAHANIE TALIB', course: 'BSN', year: '1st Year' },
    { id: '2025-111', name: 'SALISE, CARL MARLOU BIÑGIL', course: 'BSCE', year: '1st Year' },
    { id: '2025-256', name: 'SALMORIN, ALFRED R-JAY GULMATICO', course: 'BSN', year: '1st Year' },
    { id: '2025-113', name: 'SALVALOZA, CHARLES JADE EVANGELISTA', course: 'BSCE', year: '1st Year' },
    { id: '2025-353', name: 'SAMATULA, JOHARISA NAYAN', course: 'BSBA', year: '1st Year' },
    { id: '2025-343', name: 'SANCHEZ, ERIC BYRON JAVIER', course: 'BSBA', year: '1st Year' },
    { id: '2025-363', name: 'SANTOS, FRANZEL KAYE ASOTIGUE', course: 'PROF ED', year: '1st Year' },
    { id: '2025-061', name: 'SARA, AARON CAESAR EVANGELIO', course: 'BA Philo', year: '1st Year' },
    { id: '2025-050', name: 'SARAPODIN, JAMELA FAWZIA GRIÑO', course: 'BSN', year: '1st Year' },
    { id: '2025-258', name: 'SARIOL, DANIELLA CASAYAS', course: 'BSCE', year: '1st Year' },
    { id: '2025-018', name: 'SEDORIOSA, JAYLOU BANTES', course: 'BSCE', year: '1st Year' },
    { id: '2025-238', name: 'SERAFINO, KASHIECA', course: 'BSA', year: '1st Year' },
    { id: '2025-078', name: 'SERAG, JILLIANE CUA', course: 'BSN', year: '1st Year' },
    { id: '2025-080', name: 'SERRANO, URIEL TADOR', course: 'BA PoS', year: '1st Year' },
    { id: '2025-196', name: 'SIATOCA, DONALYN CARBON', course: 'PROF ED', year: '1st Year' },
    { id: '2025-040', name: 'SIBUGAN, DIVINE JAMAICA SUDARIO', course: 'BEEd', year: '1st Year' },
    { id: '2025-090', name: 'SICADA, YVETTE VILLAGOMEZ', course: 'BSMA', year: '1st Year' },
    { id: '2025-206', name: 'SILADAN, GIVE ARTHOR AQUINO', course: 'BSN', year: '1st Year' },
    { id: '2025-274', name: 'SILVA, ALYSSA GIRAO', course: 'BSN', year: '1st Year' },
    { id: '2025-156', name: 'SILVESTRE, FEA DASIG', course: 'BSA', year: '1st Year' },
    { id: '2025-055', name: 'SIMBAJON, BRISSA MASENDO', course: 'BSA', year: '1st Year' },
    { id: '2025-211', name: 'SIMBAJON, JERRY FLORES', course: 'BSN', year: '1st Year' },
    { id: '2025-142', name: 'SITONES, MEAH DIANNE MIRASOL', course: 'BSEd', year: '1st Year' },
    { id: '2025-075', name: 'SOJOR, DAREN MAE SALUT', course: 'BA PoS', year: '1st Year' },
    { id: '2024-355', name: 'SOLATORIO, JUVE FRIEL AGRAVIADOR', course: 'BSBA', year: '1st Year' },
    { id: '2025-284', name: 'SOMBLINGO, CRISTIAN CHAD CORDERO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-257', name: 'SORIANO, ALEC DANE PAREÑAS', course: 'BSEcE', year: '1st Year' },
    { id: '2025-101', name: 'SORIANO, MICAH CRISELLE FAITH ASUTILLA', course: 'BSA', year: '1st Year' },
    { id: '2025-035', name: 'STA. CRUZ, JASMINE ARTISTA', course: 'BSBA', year: '1st Year' },
    { id: '2025-318', name: 'SULIGUIN, EFREN RELANADO', course: 'BSBA', year: '1st Year' },
    { id: '2025-021', name: 'SUMAGIT, MICO LUAYON', course: 'BSN', year: '1st Year' },
    { id: '2025-064', name: 'SUPNET, FRANCIS JOHN BAYON', course: 'BA Philo', year: '1st Year' },
    { id: '2025-261', name: 'TAAS, KYLA SHANE REYNO', course: 'BSCE', year: '1st Year' },
    { id: '2025-007', name: 'TABILLA, NICOLE TOLENTINO', course: 'BSBA', year: '1st Year' },
    { id: '2022-213', name: 'TABORA, KURT FRANCIS FLORESTA', course: 'BSIT', year: '1st Year' },
    { id: '2025-229', name: 'TAJOLOSA, DONNA BELLE TAMONAN', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-194', name: 'TALAVER, YASMEN GWYNETH BUGTAY', course: 'BSBA', year: '1st Year' },
    { id: '2025-243', name: 'TAMPOY, CHLOE JANE UMPAD', course: 'BSBA', year: '1st Year' },
    { id: '2025-076', name: 'TANAKA, SAKURA VILLANUEVA', course: 'BSCE', year: '1st Year' },
    { id: '2025-063', name: 'TANALGO, YSRAEL ANTONIO LANCE', course: 'BSCE', year: '1st Year' },
    { id: '2025-167', name: 'TAYAPAD, CEDRIC JAMES DUREMDES', course: 'BSIT', year: '1st Year' },
    { id: '2025-185', name: 'TEQUIN, JUSTINE LEI VILLOGA', course: 'BSCE', year: '1st Year' },
    { id: '2025-299', name: 'TORANEO, LAURENCE ABANTES', course: 'BSCE', year: '1st Year' },
    { id: '2025-125', name: 'TORITA, JOHN MARLOU MOJAL', course: 'BPEd', year: '1st Year' },
    { id: '2025-351', name: 'TUBURAN, JET RHO BOLORON', course: 'BSCE', year: '1st Year' },
    { id: '2025-288', name: 'TUYOR, LUIS ADRIAN ARAMBALA', course: 'BSCE', year: '1st Year' },
    { id: '2025-317', name: 'UDA, VIRGILIO ALBINO', course: 'BSBA', year: '1st Year' },
    { id: '2025-226', name: 'UMALI, SHAYNE FRANCIS SINGCO', course: 'BPEd', year: '1st Year' },
    { id: '2025-160', name: 'UNABIA, CLENT JOHNCEL SINGCO', course: 'BSIT', year: '1st Year' },
    { id: '2025-220', name: 'VALENCIA, EDIZ FAYE BADILLA', course: 'BSN', year: '1st Year' },
    { id: '2025-276', name: 'VALLES, JIANNE CARLO GAABUCAYAN', course: 'BSN', year: '1st Year' },
    { id: '2025-098', name: 'VELARDE, ANGEL KYLE COLLADO', course: 'BSA', year: '1st Year' },
    { id: '2025-193', name: 'VELARDE, PRINCE KERT BASILAN', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-005', name: 'VELOS, ALLEAH GRACE DOLIDO', course: 'BSA', year: '1st Year' },
    { id: '2025-241', name: 'VERGARA, HYNNRICH', course: 'BSA', year: '1st Year' },
    { id: '2025-117', name: 'VICTORIA, XYREN MAE DOYSABAS', course: 'BSA', year: '1st Year' },
    { id: '2025-199', name: 'VIDAL, ERICA CHRISTEE MAE GONZALES', course: 'PROF ED', year: '1st Year' },
    { id: '2025-059', name: 'VILLALON, ASHER ZACCHARY JADAN', course: 'BA Philo', year: '1st Year' },
    { id: '2025-140', name: 'VILLARUEL, GRACE DARLE', course: 'BSEd', year: '1st Year' },
    { id: '2025-013', name: 'WABINGGA, CHARIES DUA', course: 'BSBA', year: '1st Year' },
    { id: '2025-275', name: 'WEILL, ALEXANDRA THESSA MARIE', course: 'BA PoS', year: '1st Year' },
    { id: '2025-051', name: 'YBAÑEZ, MIA CATALAN', course: 'PROF ED', year: '1st Year' },
    { id: '2025-173', name: 'ZAMORA, RANZ IVAN ESCOPALAO', course: 'BSMA', year: '1st Year' },
    { id: '2025-065', name: 'ZARAGOSA, JIMREX FAJURANO', course: 'BA Philo', year: '1st Year' }
  ];

  const results = {
    total: students.length,
    added: 0,
    skipped: 0,
    errors: 0,
    skippedStudents: [] as string[]
  };

  for (const student of students) {
    try {
      // Check if student already exists by ID
      const existingById = await studentService.findStudentByBarcode(student.id, 'notre-dame');
      
      if (existingById) {
        results.skipped++;
        results.skippedStudents.push(`${student.id} - ${student.name} (student ID already exists)`);
        continue;
      }

      // Check if student already exists by exact name
      const allStudents = await studentService.getStudents();
      const existingByName = allStudents.find(s => 
        s.name.toUpperCase() === student.name.toUpperCase() && 
        s.library === 'notre-dame'
      );
      
      if (existingByName) {
        results.skipped++;
        results.skippedStudents.push(`${student.id} - ${student.name} (duplicate name: already exists as ${existingByName.studentId})`);
        continue;
      }

      // Add student
      await studentService.addStudent({
        name: student.name,
        studentId: student.id,
        course: student.course,
        year: student.year,
        department: getDepartmentFromCourse(student.course),
        userType: 'student',
        studentType: 'college',
        level: 'college',
        library: 'notre-dame'
      });

      results.added++;
      
      // Small delay to avoid overwhelming the system
      await new Promise(resolve => setTimeout(resolve, 10));
      
    } catch (error) {
      console.error(`Error adding ${student.id}:`, error);
      results.errors++;
      results.skippedStudents.push(`${student.id} - ${student.name} (error: ${error})`);
    }
  }

  return results;
};
