import { studentService } from '@/services/studentService';

// Department mapping based on course codes
const getDepartmentFromCourse = (course: string): string => {
  const courseUpper = course.toUpperCase();
  
  // CECE (College of Engineering and Civil Engineering)
  if (['BSCE', 'BSEE', 'BSECE', 'BSECE', 'BSME', 'BSCHE', 'BSIE', 'BSCPE'].includes(courseUpper)) {
    return 'CECE';
  }
  
  // CBA (College of Business Administration)
  if (['BSBA', 'BSA', 'BSMA', 'BSCA', 'BSE'].includes(courseUpper)) {
    return 'CBA';
  }
  
  // CTELAN (College of Technology, Education, Liberal Arts, and Nursing)
  // This includes IT, Education, Liberal Arts, Nursing, etc.
  return 'CTELAN';
};

export const bulkImportStudents2ndYear = async () => {
  const students = [
    { id: '2024-081', name: 'ABATAY, VEA MARIE SIMENE', course: 'BSN', year: '2nd Year' },
    { id: '2025-053', name: 'ABELLA, KHAINA SHANE GEALON', course: 'BSN', year: '2nd Year' },
    { id: '2024-181', name: 'ABINASA, HERDY LOUIS BANGOT', course: 'BSCE', year: '2nd Year' },
    { id: '2024-124', name: 'ACOT, FAITH ASHLEY ALPARO', course: 'BA PoS', year: '2nd Year' },
    { id: '2023-390', name: 'ADLA-ON, NICOLE', course: 'BSEd', year: '2nd Year' },
    { id: '2024-197', name: 'AGRABIO, ANGELENE RAMOS', course: 'BSN', year: '2nd Year' },
    { id: '2023-351', name: 'AGTAS, RENIEL BACUDO', course: 'BSIT', year: '2nd Year' },
    { id: '2024-178', name: 'AHON, KEIZIAH MHARIE DANILA', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-101', name: 'ALAYON, CATHERINE ANNE MEGALBIN', course: 'BSA', year: '2nd Year' },
    { id: '2024-015', name: 'ALEGRIA, RICO JAY AGUIRRE', course: 'BSA', year: '2nd Year' },
    { id: '2024-167', name: 'ALFARO, FRANZENE JAHNN PEPITO', course: 'BSN', year: '2nd Year' },
    { id: '2024-021', name: 'ALMONIA, SAMANTHA ROSE TORREJAS', course: 'BSA', year: '2nd Year' },
    { id: '2024-067', name: 'ALPARAQUE, JULIA SOLEDAD', course: 'BSEd', year: '2nd Year' },
    { id: '2024-005', name: 'ALUCILJA, KEZIAH JEMIMA MINGUILLO', course: 'BSN', year: '2nd Year' },
    { id: '2024-048', name: 'AMARILLO, JANE CALIS', course: 'BSBA', year: '2nd Year' },
    { id: '2023-257', name: 'AMORES, RUSSEL MANGAO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-283', name: 'ANDIK, JABER AMBALGAN', course: 'BA PoS', year: '2nd Year' },
    { id: '2023-127', name: 'ANDOT, ALEXAH SHANE PONTONGAN', course: 'BSCE', year: '2nd Year' },
    { id: '2023-168', name: 'ANDRES, KARL PATRICK TABAÑAG', course: 'BSCE', year: '2nd Year' },
    { id: '2024-160', name: 'ANDRES, PRECIOUS LARA TABAÑAG', course: 'BSCE', year: '2nd Year' },
    { id: '2024-055', name: 'ANTONIO, JULIAN PATRICK CHAN', course: 'BSIT', year: '2nd Year' },
    { id: '2024-086', name: 'APIAS, RICOLIVINCE DIANONGCO', course: 'BSIT', year: '2nd Year' },
    { id: '2023-153', name: 'AQUINO, KLENT EDISON PARABA', course: 'BPEd', year: '2nd Year' },
    { id: '2023-267', name: 'ARDINA, CHRISTIAN LLOYD DAHAN', course: 'BSIT', year: '2nd Year' },
    { id: '2024-122', name: 'ARROYO, KEITH RYANN TABALINA', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-198', name: 'ATONDUCAN, KAROL CHARISSE MANA-AY', course: 'BSN', year: '2nd Year' },
    { id: '2025-271', name: 'AUREL, FRANCIS JAKE GAYONOCHE', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-211', name: 'BABILONIA, JAN ANDRE TACITAC', course: 'BSCS', year: '2nd Year' },
    { id: '2024-154', name: 'BACAT, JANZY ANGGANA', course: 'BSBA', year: '2nd Year' },
    { id: '2024-266', name: 'BACSAN, CARLO JAY RAMADA', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-037', name: 'BACUS, REYLE YSSABELLE COQUILLA', course: 'BSCE', year: '2nd Year' },
    { id: '2024-184', name: 'BADAL, JEROME MAMALUBA', course: 'BSN', year: '2nd Year' },
    { id: '2025-338', name: 'BADILLA, JENICA KATHLEEN CANON', course: 'BSN', year: '2nd Year' },
    { id: '2024-206', name: 'BADLIS, LOWRENCES GABRIEL', course: 'BSA', year: '2nd Year' },
    { id: '2024-041', name: 'BAGUIO, JUNECIL DELONA', course: 'BSMA', year: '2nd Year' },
    { id: '2024-204', name: 'BAGUIO, NASH JESON GATAN', course: 'BSBA', year: '2nd Year' },
    { id: '2025-328', name: 'BAIS, HEAVENSCENT ANDO', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-050', name: 'BAJENTING, JOMARIE CABANLAS', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-166', name: 'BALIOS, MARY CLAIRE GERODIAS', course: 'BSMA', year: '2nd Year' },
    { id: '2024-284', name: 'BALONDA, KERBY ANGELO BETITA', course: 'BSIT', year: '2nd Year' },
    { id: '2024-135', name: 'BANAN, SOFHIA ANGELA YABUT', course: 'BSN', year: '2nd Year' },
    { id: '2024-351', name: 'BARBASAN, SHANE SICABALO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-017', name: 'BARGO, JILLIAN AVRIL BACUAG', course: 'BSIT', year: '2nd Year' },
    { id: '2024-261', name: 'BARSARSA, DIVINE CAMBALON', course: 'BSBA', year: '2nd Year' },
    { id: '2024-245', name: 'BARUIS, DARYL BANGCAYLAN', course: 'BSBA', year: '2nd Year' },
    { id: '2024-209', name: 'BAUTISTA, PAUL MCGINLEY ESTREBOR', course: 'BSCS', year: '2nd Year' },
    { id: '2024-152', name: 'BAUTISTA, SHERWYN BRYLLE QUIMBO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-111', name: 'BEDAÑO, RAY KENNETH COLOT', course: 'BSCE', year: '2nd Year' },
    { id: '2024-076', name: 'BELISARIO, ALVEY JHON LENDIO', course: 'BSIT', year: '2nd Year' },
    { id: '2023-173', name: 'BELONIO, KAILA CAPISTRANO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-275', name: 'BENDEJO, LUIS EMMANUEL SARIOL', course: 'BSEd', year: '2nd Year' },
    { id: '2024-370', name: 'BERDOS, DANIEL', course: 'BEEd', year: '2nd Year' },
    { id: '2024-134', name: 'BERNAL, STEVEN JAY LANGUIDO', course: 'BSCE', year: '2nd Year' },
    { id: '2024-034', name: 'BERNALDEZ, SEID AZREIH', course: 'BSN', year: '2nd Year' },
    { id: '2024-142', name: 'BETIL, JOMAREY DELOS REYES', course: 'BSBA', year: '2nd Year' },
    { id: '2023-318', name: 'BIEREN, HIROSHI MUNDOG', course: 'BSCE', year: '2nd Year' },
    { id: '2024-219', name: 'BITALAS, LESLIE ANNE SUMAYA', course: 'BSN', year: '2nd Year' },
    { id: '2024-230', name: 'BONGABONG, NOVAJANE MARFE', course: 'BSBA', year: '2nd Year' },
    { id: '2024-120', name: 'BUALAN, PRINCESS KYLLA CADUNGOG', course: 'BSA', year: '2nd Year' },
    { id: '2024-018', name: 'BUCHAN, KEANE INOJ DELIMA', course: 'BSIT', year: '2nd Year' },
    { id: '2024-028', name: 'BUGAY, KIM JASPHER YARTE', course: 'BEEd', year: '2nd Year' },
    { id: '2024-255', name: 'BULI, JOANNA ROSE BARRO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-260', name: 'BULI, LEA ROSE BARRO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-099', name: 'BURCAO, ZECH SWELU NGAMOY', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-196', name: 'CABALLERO, CHRIOSOL MAR OCAY', course: 'BSCE', year: '2nd Year' },
    { id: '2024-289', name: 'CABAÑAS, VENUS MARRIANNE LAPURA', course: 'BSN', year: '2nd Year' },
    { id: '2024-129', name: 'CABANILLA, JENESSA MABANDOS', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-290', name: 'CABANLAS, ALTHIA EGOT', course: 'BSCE', year: '2nd Year' },
    { id: '2023-136', name: 'CABARON, DENZ CHRISTIAN CASTILLANES', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-274', name: 'CABARON, IRISH ROQUE', course: 'BSBA', year: '2nd Year' },
    { id: '2024-236', name: 'CABILLO, ALJON PANDIO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-212', name: 'CABILLON, CHRISTIA YVONNE PUERTO', course: 'BSCE', year: '2nd Year' },
    { id: '2024-112', name: 'CACATIAN, FRANCHESCA YSABEL PALABRICA', course: 'BSN', year: '2nd Year' },
    { id: '2024-040', name: 'CAGAPE, GEOFF CARLSON ENOPIA', course: 'BSA', year: '2nd Year' },
    { id: '2024-097', name: 'CAGAS, ANGELOU ORPIA', course: 'BSN', year: '2nd Year' },
    { id: '2024-268', name: 'CAGAS, IVEN PETAO', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-238', name: 'CAJURAO, PRINCE JADE LAGDAMEN', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-299', name: 'CALABROSO, GEAINNE MARIE MAN-ON', course: 'BSCE', year: '2nd Year' },
    { id: '2024-115', name: 'CALAMBA, MARIEL JANIEL DINGAL', course: 'BSBA', year: '2nd Year' },
    { id: '2024-133', name: 'CALBAZA, JOHN JENESIS ARDIENTE', course: 'BSMA', year: '2nd Year' },
    { id: '2024-087', name: 'CALIBARA, MARY CLAIRE ALMENDRALEJO', course: 'BSEd', year: '2nd Year' },
    { id: '2024-093', name: 'CALICARAN, MURFIE LEE JAVIER', course: 'BSA', year: '2nd Year' },
    { id: '2023-352', name: 'CAMENSA, STEVEN JAN VILAR', course: 'BSIT', year: '2nd Year' },
    { id: '2023-054', name: 'CAMORO, BONJO TEH', course: 'BSIT', year: '2nd Year' },
    { id: '2024-232', name: 'CARDENAS, KLOE MARGARETTE AGAPAY', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-104', name: 'CAZEÑAS, JUSTINE MARTINEZ', course: 'BSA', year: '2nd Year' },
    { id: '2024-054', name: 'CERMINO, ZOE ZACHARY ALILING', course: 'BSBA', year: '2nd Year' },
    { id: '2024-138', name: 'CERVANTES, ARJERRY JOHN DADIVAS', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-213', name: 'CHAVEZ, LORENCE ABRIQUE', course: 'BSEcE', year: '2nd Year' },
    { id: '2023-276', name: 'CORDERO, MICHAEL REYMOR LADAO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-252', name: 'CUBERO, JOSEPH PASTOR GENERALLA', course: 'BSCE', year: '2nd Year' },
    { id: '2024-280', name: 'CUBERO, QUINZ BENEDICT ABANILLA', course: 'BSBA', year: '2nd Year' },
    { id: '2024-073', name: 'DAANO, JESSA BILLONES', course: 'BSA', year: '2nd Year' },
    { id: '2024-148', name: 'DAHAN, JHON STEVEN ARGAME', course: 'BSBA', year: '2nd Year' },
    { id: '2023-362', name: 'DALIGCON, RYAN GERARD DELA TORRE', course: 'BSCE', year: '2nd Year' },
    { id: '2024-051', name: 'DALIGDIG, GODFREY NEIL ESCOLLAR', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-231', name: 'DAPITO, GIL DAPAN', course: 'BSBA', year: '2nd Year' },
    { id: '2024-139', name: 'DAQUIPIL, PV JEAN FERNANDEZ', course: 'BSN', year: '2nd Year' },
    { id: '2024-237', name: 'DAYAGANON, CLARK PELARION', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-191', name: 'DE ASIS, ANGELICA MEA GALLENTES', course: 'BSBA', year: '2nd Year' },
    { id: '2024-002', name: 'DE GUTIERREZ, ALTHEA RUTH AMANCIO', course: 'BSN', year: '2nd Year' },
    { id: '2024-171', name: 'DE GUZMAN, CHRISTINA ANGELA MARGARETTE VARGAS', course: 'BA Comm', year: '2nd Year' },
    { id: '2024-158', name: 'DE JESUS, DOROTHY JULIENNE BALANSAG', course: 'BSN', year: '2nd Year' },
    { id: '2024-042', name: 'DE VERA, LESLIE JANE OCAMPO', course: 'BSA', year: '2nd Year' },
    { id: '2023-035', name: 'DECOLONGON, CARL PRECIOSO', course: 'BSCS', year: '2nd Year' },
    { id: '2024-052', name: 'DELA CRUZ, CLEEN ORTIZO', course: 'BSN', year: '2nd Year' },
    { id: '2024-077', name: 'DELEGENCIA, CLIVYN QUITEL', course: 'BA Comm', year: '2nd Year' },
    { id: '2024-011', name: 'DELFIN, JASMEN TORRES', course: 'BSA', year: '2nd Year' },
    { id: '2024-270', name: 'DEMAFILES, RUSTOM JAY HISO', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-297', name: 'DENAGA, REAH MARIE TUARIO', course: 'BSN', year: '2nd Year' },
    { id: '2024-144', name: 'DIMAAGOS, PRINCES AMERA DILANGALEN', course: 'BSN', year: '2nd Year' },
    { id: '2025-346', name: 'DIMACUTAC, JOHN MARK RUFINO', course: 'BSCE', year: '2nd Year' },
    { id: '2024-070', name: 'DINGCONG, ABEGAIL DIGMAN', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-053', name: 'DOMINGO, KITZ LEONARD BORRA', course: 'BEEd', year: '2nd Year' },
    { id: '2024-265', name: 'DONAIRE, JOERNIE', course: 'BA Comm', year: '2nd Year' },
    { id: '2024-029', name: 'DUMANIG, JOHN MICHAEL JIMENEZ', course: 'BSMA', year: '2nd Year' },
    { id: '2024-025', name: 'ECHAVEZ, FREINCE VERN JOY BORNASAL', course: 'BSBA', year: '2nd Year' },
    { id: '2024-203', name: 'ELIZONDO, ALTHEA LOUISE VILLANUEVA', course: 'BSN', year: '2nd Year' },
    { id: '2024-248', name: 'ELIZONDO, ZAQ ISAIAH PALEC', course: 'BSN', year: '2nd Year' },
    { id: '2024-132', name: 'ELUSFA, REV PATRICK SANTILLAN', course: 'BSCpE', year: '2nd Year' },
    { id: '2023-328', name: 'ENCARNACION, VIC VINCENT OCHAVILLO', course: 'BSCE', year: '2nd Year' },
    { id: '2024-369', name: 'ENOT, ALEXANDRA', course: 'BSBA', year: '2nd Year' },
    { id: '2023-293', name: 'ESMINO, CHODE FERNANDO MONDERO', course: 'BSIT', year: '2nd Year' },
    { id: '2024-277', name: 'ESPESO, JHANRY PHILIP DABALOS', course: 'BSCS', year: '2nd Year' },
    { id: '2024-352', name: 'ESPINA, KYLIE GRACE ACAIN', course: 'BSN', year: '2nd Year' },
    { id: '2024-119', name: 'ESTEBAN, LOUIE JAY LUSTRE', course: 'BSEd', year: '2nd Year' },
    { id: '2024-188', name: 'ESTEPA, NEIL IVAN GREGORIO', course: 'BSIT', year: '2nd Year' },
    { id: '2024-026', name: 'ESTRADA, XYLA MEMARION', course: 'BSN', year: '2nd Year' },
    { id: '2024-145', name: 'EVANGELIO, GENRELLA MITCH GENSOLE', course: 'BSEd', year: '2nd Year' },
    { id: '2024-075', name: 'FAJARDO, PRINCESS CHRISTINE ALBIALDE', course: 'BSEd', year: '2nd Year' },
    { id: '2023-380', name: 'FERNANDEZ, CRISTINE KAYE GALLENTES', course: 'BSBA', year: '2nd Year' },
    { id: '2024-068', name: 'FERNANDEZ, KIRSTEN GAYLE GARAGAN', course: 'BSN', year: '2nd Year' },
    { id: '2024-092', name: 'FERNANDEZ, LEAH GRACE NEQUIN', course: 'BSA', year: '2nd Year' },
    { id: '2024-036', name: 'FLORES, KURT LAWRENCE RAGOSTA', course: 'BSA', year: '2nd Year' },
    { id: '2024-083', name: 'FLORES, REYNO GALLANO', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-007', name: 'FRANCISCO, SAM ABAPO', course: 'BSCE', year: '2nd Year' },
    { id: '2024-164', name: 'FUENTES, EARL JELORD NAYGA', course: 'BSBA', year: '2nd Year' },
    { id: '2024-058', name: 'GACANG, SHERWIN', course: 'BSCE', year: '2nd Year' },
    { id: '2024-024', name: 'GALON, SOFIA CHRISSIAH JAVIER', course: 'BSN', year: '2nd Year' },
    { id: '2024-256', name: 'GALVEZ, JOHN KENNETH MAGHARI', course: 'BSBA', year: '2nd Year' },
    { id: '2024-071', name: 'GARCENILA, VENICE ILUSTRE', course: 'BEEd', year: '2nd Year' },
    { id: '2024-223', name: 'GASES, CHARLES DANIELLE AMARO', course: 'BPEd', year: '2nd Year' },
    { id: '2023-247', name: 'GATPAYAD, JHON PAUL PELARCO', course: 'BSIT', year: '2nd Year' },
    { id: '2024-032', name: 'GEMENTIZA, BENZ LOUIE SAPALO', course: 'BSN', year: '2nd Year' },
    { id: '2024-038', name: 'GEVER, ANDREI CARLOS LADAY', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-356', name: 'GONSANG, ZAIRAH PETALCO', course: 'BA Comm', year: '2nd Year' },
    { id: '2024-150', name: 'GONZALES, MAC ZEUS NOBLEZA', course: 'BSA', year: '2nd Year' },
    { id: '2024-281', name: 'GONZALES, PERRY GARCIA', course: 'BSCE', year: '2nd Year' },
    { id: '2024-173', name: 'GRANDE, FEIL LOREANNE DANTE', course: 'BSBA', year: '2nd Year' },
    { id: '2024-013', name: 'GUABONG, TESSEL MARRY MABALOT', course: 'BSCE', year: '2nd Year' },
    { id: '2024-153', name: 'HAGANOS, JOHN RICH RUBINO', course: 'BSA', year: '2nd Year' },
    { id: '2024-049', name: 'HERMAC, MAETHAN JHON BADILLA', course: 'BSIT', year: '2nd Year' },
    { id: '2024-296', name: 'ITORRALBA, MICHAEL JOHN ANTONIO', course: 'BSN', year: '2nd Year' },
    { id: '2024-234', name: 'IWAY, CHINA MAE ATILANO', course: 'BSEd', year: '2nd Year' },
    { id: '2024-273', name: 'JALAPON, ASHLEY SAFIRA BADONGEN', course: 'BSEd', year: '2nd Year' },
    { id: '2024-199', name: 'JAMORABON, ELLAIZA JIEZEL MUNDOG', course: 'BSEd', year: '2nd Year' },
    { id: '2025-247', name: 'JANORAS, JULIUS CEAZAR PADIOS', course: 'BSN', year: '2nd Year' },
    { id: '2024-066', name: 'JUDILLA, AICEL ZIAH GALLAZA', course: 'BSA', year: '2nd Year' },
    { id: '2025-215', name: 'LABRADOR, STEPHEN PANTIA', course: 'BSN', year: '2nd Year' },
    { id: '2024-090', name: 'LAGATA, LORELIE BILOG', course: 'BSMA', year: '2nd Year' },
    { id: '2024-079', name: 'LALLEN, JERICK LLOYD CASAS', course: 'BEEd', year: '2nd Year' },
    { id: '2024-360', name: 'LAMOSTE, LIANNE ROSE ROMERO', course: 'BSA', year: '2nd Year' },
    { id: '2024-250', name: 'LANO, FATMAWATI GALIDO', course: 'BSN', year: '2nd Year' },
    { id: '2024-151', name: 'LAPI, JANE MAR ORATE', course: 'BSEd', year: '2nd Year' },
    { id: '2024-156', name: 'LARAÑO, CARRYL ANN MARAÑON', course: 'BPEd', year: '2nd Year' },
    { id: '2024-147', name: 'LEBRILLO, SAM DANIEL CUEVAS', course: 'BSCE', year: '2nd Year' },
    { id: '2024-045', name: 'LEONG, KIM GEMOTA', course: 'BSCE', year: '2nd Year' },
    { id: '2024-172', name: 'LEONIDA, VIE BRYANTH TIBAY', course: 'BSCE', year: '2nd Year' },
    { id: '2024-057', name: 'LICATAN, JEANNA MARIE TRINIDAD', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-091', name: 'LLAGAS, CARSON LALLEN', course: 'BSBA', year: '2nd Year' },
    { id: '2023-167', name: 'LLANTO, REY ANN BAQUILO', course: 'BSEcE', year: '2nd Year' },
    { id: '2024-116', name: 'LUCASAN, ROBERT JAY CABUDAY', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-363', name: 'LUENGAS, ROSEMARIE', course: 'BSBA', year: '2nd Year' },
    { id: '2024-242', name: 'LUSPO, AGA FRANCIS PAÑA', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-293', name: 'MAANGUE, KEI LOPEZ', course: 'BSBA', year: '2nd Year' },
    { id: '2024-372', name: 'MACAPUNDAG, ASIZAH COMONDARA', course: 'BSCE', year: '2nd Year' },
    { id: '2023-370', name: 'MADATO, PRINCE RHOBERT ESMAEL', course: 'BSCE', year: '2nd Year' },
    { id: '2024-100', name: 'MADAYAG, MAR-JUSTINE CAMARILLO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-137', name: 'MAGALLANES, TJ HAN GAURAN', course: 'BSEd', year: '2nd Year' },
    { id: '2024-103', name: 'MAGBANUA, RALPH LAURENCE PEDREGOSA', course: 'BSBA', year: '2nd Year' },
    { id: '2024-098', name: 'MAGHARI, JOHN ADRIAN ANTIPUESTO', course: 'BSEcE', year: '2nd Year' },
    { id: '2024-267', name: 'MAGUATE, AL CLARENCE TABORA', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-027', name: 'MANUEL, TWYNZXYNTH LLYNN DAQUIS', course: 'BSCE', year: '2nd Year' },
    { id: '2024-123', name: 'MAYOR, ROBERT JASON BULSECO', course: 'BSA', year: '2nd Year' },
    { id: '2024-060', name: 'MEDINA, JERMAINE PIQUERO', course: 'BSA', year: '2nd Year' },
    { id: '2024-109', name: 'MERDON, ERICK EMMANUEL ACOSTA', course: 'BSCE', year: '2nd Year' },
    { id: '2024-205', name: 'MOLO, CEDRIC EMMANUEL ENDAYA', course: 'BSN', year: '2nd Year' },
    { id: '2024-200', name: 'MONTERO, CRISTEL ANGELA DASALLA', course: 'BSN', year: '2nd Year' },
    { id: '2024-217', name: 'MUDANZA, KRYSLER LEX TO-ONG', course: 'BSBA', year: '2nd Year' },
    { id: '2024-162', name: 'MUYCO, CASSANDRA ALEXINNE SAYSON', course: 'BSMA', year: '2nd Year' },
    { id: '2024-253', name: 'MUYCO, NIKKI SHIENE SIASOL', course: 'BSBA', year: '2nd Year' },
    { id: '2024-295', name: 'NACARIO, KAREL KATE BACSON', course: 'BSEd', year: '2nd Year' },
    { id: '2024-294', name: 'NAHILAT, JASPHER JAN VISERA', course: 'BSBA', year: '2nd Year' },
    { id: '2024-354', name: 'NATIVIDAD, CINDY YAGAO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-155', name: 'NEDAMO, JOHN DERICK SALCEDO', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-269', name: 'NEGRILLO, IAN CARL LIASOS', course: 'BSEd', year: '2nd Year' },
    { id: '2024-008', name: 'NEMEÑO, JIA GALLANO', course: 'BSN', year: '2nd Year' },
    { id: '2024-031', name: 'NICOR, ROREIN JOHNSON MENDOZA', course: 'BSIT', year: '2nd Year' },
    { id: '2024-061', name: 'OASAY, JOHN PATRICK BALURA', course: 'BSEd', year: '2nd Year' },
    { id: '2024-127', name: 'ONG, JOCELYN ANN PASON', course: 'BSA', year: '2nd Year' },
    { id: '2023-174', name: 'ORGO, IVAN KEIL CAPISTRANO', course: 'BSIT', year: '2nd Year' },
    { id: '2024-019', name: 'ORTEGA, MJ MARK ANGELO', course: 'BSCS', year: '2nd Year' },
    { id: '2024-085', name: 'OSORNO, PRINCE ERROL ENAD', course: 'BSCE', year: '2nd Year' },
    { id: '2024-358', name: 'PACLIBAR, MONIQUE ANGELA PROVIDO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-208', name: 'PADUA, DYANNE MAY SUFICIENCIA', course: 'BSN', year: '2nd Year' },
    { id: '2024-131', name: 'PAGATPATAN, LOREN SALISID', course: 'BSBA', year: '2nd Year' },
    { id: '2024-128', name: 'PAGUICAN, BEEJAY QUIROS', course: 'BSA', year: '2nd Year' },
    { id: '2023-360', name: 'PAMA, RUTH ALLIAH MARIEH MAGTULIS', course: 'BSN', year: '2nd Year' },
    { id: '2024-259', name: 'PANTINOPLE, FRIENSKELEYN ARANZADO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-136', name: 'PARAL, ALLEN CRIS ENOC', course: 'BSEcE', year: '2nd Year' },
    { id: '2024-240', name: 'PARCON, JOHN ANGELO MAGHARI', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-089', name: 'PAUYA, CARMELA ALEXIA PEDREGOSA', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-298', name: 'PEQUIT, MIYA DANZEN GALLENO', course: 'BSIT', year: '2nd Year' },
    { id: '2024-023', name: 'PERALTA, NEIL PATRICK ABANILLA', course: 'BSIT', year: '2nd Year' },
    { id: '2024-140', name: 'PERIALDE, CLENA ERA IRLANDEZ', course: 'BSEd', year: '2nd Year' },
    { id: '2024-185', name: 'PILARCA, ARNOLD ESPANOLA', course: 'BSEcE', year: '2nd Year' },
    { id: '2024-117', name: 'PILARE, JHADE FRITZ SAMANTE', course: 'BSCE', year: '2nd Year' },
    { id: '2024-193', name: 'PINEDA, RENZ SIASOL', course: 'BSCE', year: '2nd Year' },
    { id: '2024-357', name: 'PINGAN, JOAN BALDON', course: 'BSEd', year: '2nd Year' },
    { id: '2024-113', name: 'PORRAS, KRISZIA KAYE CERBAS', course: 'BSEd', year: '2nd Year' },
    { id: '2024-201', name: 'PORRAS, KRYSTAL HOPE DIONISIO', course: 'BSCE', year: '2nd Year' },
    { id: '2024-094', name: 'QUIAÑO, MIGUEL KAROL ALMIRANTE', course: 'BSCE', year: '2nd Year' },
    { id: '2024-224', name: 'QUIBINGCO, KYLE ESPAÑOLA', course: 'BSBA', year: '2nd Year' },
    { id: '2025-218', name: 'QUILARIO, SAITH YVETTE SUERTE', course: 'BSN', year: '2nd Year' },
    { id: '2024-257', name: 'REBUTA, HASHEENA CRUZ', course: 'BSCE', year: '2nd Year' },
    { id: '2024-210', name: 'RECALE, HARRY PASILBAS', course: 'BSCS', year: '2nd Year' },
    { id: '2024-228', name: 'REDONDO, VINCE JAYSON DICDIQUIN', course: 'BSIT', year: '2nd Year' },
    { id: '2024-030', name: 'REFORMINA, SHENA CRISTOBAL', course: 'BSCE', year: '2nd Year' },
    { id: '2024-194', name: 'RELACION, JOHN LOYD', course: 'BSBA', year: '2nd Year' },
    { id: '2024-226', name: 'REMOROZA, JOVINA TABIFRANCA', course: 'BSEd', year: '2nd Year' },
    { id: '2024-179', name: 'RIGA, FRANCINE SHANE', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-059', name: 'ROA, MILES ADRIAN ABADILLA', course: 'BSMA', year: '2nd Year' },
    { id: '2024-014', name: 'RODRIGUEZ, ISABELA BEATRICE GRIÑO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-227', name: 'ROMAREZ, THEA LUZ MARGARETTE CEDEÑO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-218', name: 'RUBAS, ANDREA LOU CURAYAG', course: 'BSN', year: '2nd Year' },
    { id: '2023-051', name: 'RULONA, CHRISTIAN JAY FAJARDO', course: 'BSCE', year: '2nd Year' },
    { id: '2023-224', name: 'RULONA, IVY SHANE BENIDO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-149', name: 'SALAPE, SEAN HARRY SABAYSABAY', course: 'BSBA', year: '2nd Year' },
    { id: '2024-157', name: 'SAMILLANO, KURT IVAN ORBE', course: 'BSIT', year: '2nd Year' },
    { id: '2024-374', name: 'SAMPILO, ROEL ALISOSO', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-118', name: 'SANICO, JEOBEL NAIG', course: 'BPEd', year: '2nd Year' },
    { id: '2024-276', name: 'SANTERO, MARY CHIARA ABALLE', course: 'BSN', year: '2nd Year' },
    { id: '2024-225', name: 'SAPALON, HAMDAN SHAIR MOHAMMAD', course: 'BSCE', year: '2nd Year' },
    { id: '2023-275', name: 'SARIOL, JIANA YUKZELLE MAGDOSA', course: 'BA Comm', year: '2nd Year' },
    { id: '2024-088', name: 'SARMIENTO, KYLE NIÑO BALTAZAR', course: 'BSCE', year: '2nd Year' },
    { id: '2024-062', name: 'SATOQUIA, CLOE ANGELA SIAGO', course: 'BSN', year: '2nd Year' },
    { id: '2024-233', name: 'SAWAY, MELYN JOY LABANON', course: 'BSIT', year: '2nd Year' },
    { id: '2024-106', name: 'SEDANO, IAN JULES BALANI', course: 'BSMA', year: '2nd Year' },
    { id: '2024-221', name: 'SENCIL, HASNA ALEAH SABDULA', course: 'BSCE', year: '2nd Year' },
    { id: '2023-381', name: 'SILANGAN, MARIA JOCEN AMBINOC', course: 'BEEd', year: '2nd Year' },
    { id: '2024-202', name: 'SOLANIA, HYCINTH MAE DAGNAOS', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-010', name: 'SOMERA, HERA BELLE SORIANO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-016', name: 'SOMO, ALTHEA CAMILLE CARCILLAR', course: 'BSMA', year: '2nd Year' },
    { id: '2024-143', name: 'SULTAN, ATABAI SALIDATAN', course: 'BSN', year: '2nd Year' },
    { id: '2024-146', name: 'SUMALINOG, SAMANTHA KATE BENDEJO', course: 'BSEd', year: '2nd Year' },
    { id: '2024-170', name: 'SUMBELING, CASSANDRA ELENA MISA', course: 'BSMA', year: '2nd Year' },
    { id: '2024-222', name: 'TABANAY, SIMEON CASTAÑO', course: 'BSIT', year: '2nd Year' },
    { id: '2024-262', name: 'TABAOSAREZ, WINEAL ZAMBRA', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-035', name: 'TABARANZA, JOSIEBETH CORDERO', course: 'BSN', year: '2nd Year' },
    { id: '2024-114', name: 'TACIS, GEORLENE MARIE VITOR', course: 'BSA', year: '2nd Year' },
    { id: '2024-084', name: 'TAGOLIMOT, DAREN JANELLE JOY', course: 'BSA', year: '2nd Year' },
    { id: '2024-285', name: 'TAMAYOR, MARJUN BARBON', course: 'BPEd', year: '2nd Year' },
    { id: '2024-189', name: 'TAMONAN, INZO DIAN', course: 'BSEcE', year: '2nd Year' },
    { id: '2024-175', name: 'TAMONDONG, JAZH ADAMSON MALINGCO', course: 'BSA', year: '2nd Year' },
    { id: '2024-043', name: 'TAMPIPI, JOENALIZA PAGABANGAN', course: 'BSCE', year: '2nd Year' },
    { id: '2024-359', name: 'TANALLON, JOEF LAWRENCE AGUSTIN', course: 'BSBA', year: '2nd Year' },
    { id: '2025-181', name: 'TAPANDING, RAZEAH BAGO', course: 'BSN', year: '2nd Year' },
    { id: '2023-019', name: 'TAYAPAD, KRISTIAN TABAQUE', course: 'BSIT', year: '2nd Year' },
    { id: '2024-220', name: 'TEJEDOR, CRYSTAL JADE VALDESCO', course: 'BSBA', year: '2nd Year' },
    { id: '2023-208', name: 'TOLENTINO, FLORENCE FAYE LINGASA', course: 'BSBA', year: '2nd Year' },
    { id: '2025-123', name: 'TOLOSA, RACHELLE CORPUZ', course: 'BSCpE', year: '2nd Year' },
    { id: '2024-141', name: 'TONGCUA, MAEVIN GRACE ENCARNACION', course: 'BSA', year: '2nd Year' },
    { id: '2024-361', name: 'TORCUATOR, CASHEIKA MAURINE NADELA', course: 'BSBA', year: '2nd Year' },
    { id: '2024-047', name: 'TUPAS, ANGEL FAITH CACHUMBO', course: 'BSBA', year: '2nd Year' },
    { id: '2024-039', name: 'UNTE, SAHALIA DIMAPORO', course: 'BSA', year: '2nd Year' },
    { id: '2024-126', name: 'VALDEVIESO, CHRISLER PECONADA', course: 'BA PoS', year: '2nd Year' },
    { id: '2024-174', name: 'VALE, LOUIE JOHN GRANDE', course: 'BSBA', year: '2nd Year' },
    { id: '2024-065', name: 'VALENZUELA, ANTHONY UBALES', course: 'BSN', year: '2nd Year' },
    { id: '2025-342', name: 'VEGAFRIA, MYKE ANGELO GAPASIN', course: 'BA Philo', year: '2nd Year' },
    { id: '2024-072', name: 'VERIDIANO, AYUMI ELI GONZALES', course: 'BSA', year: '2nd Year' },
    { id: '2024-074', name: 'VESILLAS, ZEDRIC JOHN PALMARES', course: 'BSBA', year: '2nd Year' },
    { id: '2024-003', name: 'VIDAD, LANZ NIKKO LUNA', course: 'BSN', year: '2nd Year' },
    { id: '2024-096', name: 'VILLAGONZALO, MERYLL JOY BERGANTIN', course: 'BSBA', year: '2nd Year' },
    { id: '2024-080', name: 'VILLANUEVA, ATHEA JULIA VILLAGONZALO', course: 'BSA', year: '2nd Year' },
    { id: '2024-168', name: 'VILLANUEVA, NEIL OWEN ORBITA', course: 'BSMA', year: '2nd Year' },
    { id: '2025-331', name: 'VILLARIN, DIANE GRACE SAMSON', course: 'BEEd', year: '2nd Year' },
    { id: '2024-130', name: 'VILLARIN, JAMES MOSAM', course: 'BSCE', year: '2nd Year' },
    { id: '2024-235', name: 'VILLAROSA, ANGEL CHRIST\'L BACALSO', course: 'BSA', year: '2nd Year' },
    { id: '2022-143', name: 'YARRA, KORKY ROBLES', course: 'BSN', year: '2nd Year' },
    { id: '2024-165', name: 'YBAÑEZ, JULIE ANNE LABAWAN', course: 'BSA', year: '2nd Year' },
    { id: '2024-082', name: 'YBAÑEZ, LIO MIKAEL DORAL', course: 'BSIT', year: '2nd Year' },
    { id: '2023-131', name: 'ZAFRA, REGINE FAITH MAINIT', course: 'BEEd', year: '2nd Year' },
    { id: '2024-190', name: 'ZILMAR, CARL XANDER MARAÑON', course: 'BSCS', year: '2nd Year' },
    { id: '2023-367', name: 'ZULUETA, RONNALEE NAYGA', course: 'BSIT', year: '2nd Year' },
  ];

  const results = {
    total: students.length,
    added: 0,
    skipped: 0,
    errors: 0,
    skippedStudents: [] as string[]
  };

  for (const student of students) {
    try {
      // Check if student already exists by ID
      const existingById = await studentService.findStudentByBarcode(student.id, 'notre-dame');
      
      if (existingById) {
        results.skipped++;
        results.skippedStudents.push(`${student.id} - ${student.name} (student ID already exists)`);
        continue;
      }

      // Check if student already exists by exact name
      const allStudents = await studentService.getStudents();
      const existingByName = allStudents.find(s => 
        s.name.toUpperCase() === student.name.toUpperCase() && 
        s.library === 'notre-dame'
      );
      
      if (existingByName) {
        results.skipped++;
        results.skippedStudents.push(`${student.id} - ${student.name} (duplicate name: already exists as ${existingByName.studentId})`);
        continue;
      }

      // Add student
      await studentService.addStudent({
        name: student.name,
        studentId: student.id,
        course: student.course,
        year: student.year,
        department: getDepartmentFromCourse(student.course),
        userType: 'student',
        studentType: 'college',
        level: 'college',
        library: 'notre-dame'
      });

      results.added++;
      
      // Small delay to avoid overwhelming the system
      await new Promise(resolve => setTimeout(resolve, 10));
      
    } catch (error) {
      console.error(`Error adding ${student.id}:`, error);
      results.errors++;
      results.skippedStudents.push(`${student.id} - ${student.name} (error: ${error})`);
    }
  }

  return results;
};

export const bulkImportStudents2025 = async () => {
  const students = [
    { id: '2025-019', name: 'BAJENTING, KRISTEL JIEZAN ESTACIONES', course: 'BSEd', year: '1st Year' },
    { id: '2025-326', name: 'BALBUENA, KHEAN', course: 'BS Psychology', year: '1st Year' },
    { id: '2024-347', name: 'BALICO, CLYDE MAUEL PAMAN', course: 'BSA', year: '1st Year' },
    { id: '2025-010', name: 'BANDOY, KRISTINE TAOY', course: 'BSN', year: '1st Year' },
    { id: '2025-009', name: 'BANDOY, MEISHEE SHEIN', course: 'BA PoS', year: '1st Year' },
    { id: '2025-278', name: 'BANGERO, AEIRON JAMES LEGORIO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-004', name: 'BANGOT, KURT ANGELO DELA CRUZ', course: 'BSN', year: '1st Year' },
    { id: '2025-097', name: 'BANSIL, NORJANNAH SALIC', course: 'BSA', year: '1st Year' },
    { id: '2025-232', name: 'BANSILAN, ARYAN FERDAUZ MAMASABULOD', course: 'BSCE', year: '1st Year' },
    { id: '2025-334', name: 'BANZON, ROLLY JOROLAN', course: 'PROF ED', year: '1st Year' },
    { id: '2025-012', name: 'BAROT, LIANE', course: 'BS Psychology', year: '1st Year' },
    { id: '2024-346', name: 'BARRETE, JAMES LLOYD CABILOGAN', course: 'BSBA', year: '1st Year' },
    { id: '2025-145', name: 'BARRIENTOS, JYRHA KYLE ALEJANDRO', course: 'BSA', year: '1st Year' },
    { id: '2025-011', name: 'BATAL, CHRISTOPHER BRENT LOQUINTE', course: 'BSA', year: '1st Year' },
    { id: '2025-072', name: 'BAUTISTA, VEA PAGAYAO', course: 'BSEd', year: '1st Year' },
    { id: '2025-124', name: 'BAYAO, JURIE PLANG', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-036', name: 'BAYAO, JUSTIN CAUMPONGAN', course: 'BSN', year: '1st Year' },
    { id: '2025-109', name: 'BAYAWAN, JENS BENEDICT SILLADOR', course: 'BSCE', year: '1st Year' },
    { id: '2025-289', name: 'BAYAWAN, PEJAY LUMAYON', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-280', name: 'BEDICO, JERICHO TUNGCALING', course: 'BSMA', year: '1st Year' },
    { id: '2025-139', name: 'BELARMINO, ELIZA KATE PAGUICAN', course: 'BSMA', year: '1st Year' },
    { id: '2025-263', name: 'BELONIO, RUTCHIE CAPISTRANO', course: 'BSIT', year: '1st Year' },
    { id: '2025-233', name: 'BENDO, JOHN MAVERICK JAMON', course: 'BSIT', year: '1st Year' },
    { id: '2025-314', name: 'BERAME, IVAN ANDREW ESCURO', course: 'BSIT', year: '1st Year' },
    { id: '2025-157', name: 'BERANGEL, JOSHUA REBUSIT', course: 'BSCE', year: '1st Year' },
    { id: '2025-180', name: 'BERMUDO, ZIA KEITH PADASAS', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-277', name: 'BERNALDEZ, RYZA ANNABELLE PINAPIT', course: 'PROF ED', year: '1st Year' },
    { id: '2025-205', name: 'BERZAMINA, MARK ZEMRIO QUIJANO', course: 'BSCE', year: '1st Year' },
    { id: '2025-197', name: 'BIACA, JONATHAN GUMBAN', course: 'PROF ED', year: '1st Year' },
    { id: '2025-158', name: 'BIEREN, CHARMIEL JAINAR', course: 'BSCE', year: '1st Year' },
    { id: '2025-093', name: 'BOLIVAR, ABE JILL BUNDA', course: 'BSN', year: '1st Year' },
    { id: '2025-319', name: 'BONILLA, TIMOTHY JOSEPH BANAC', course: 'BSIT', year: '1st Year' },
    { id: '2025-333', name: 'BORJA, ALEXA PEARL BLAYA', course: 'BA PoS', year: '1st Year' },
    { id: '2025-200', name: 'BORRES, ROSE HERBOLINGO', course: 'PROF ED', year: '1st Year' },
    { id: '2025-234', name: 'BRITOS, CHLOE TAMONAN', course: 'BSBA', year: '1st Year' },
    { id: '2025-300', name: 'BUNED, RENA JEAN SASANA', course: 'BSBA', year: '1st Year' },
    { id: '2025-306', name: 'BUNIEL, BEN JOSEPH DONGUINES', course: 'BSEd', year: '1st Year' },
    { id: '2025-183', name: 'CABAGNOT, KARL JAMES CARCILLAR', course: 'BPEd', year: '1st Year' },
    { id: '2025-001', name: 'CABANAYAN, NADINE MIÑAO', course: 'PROF ED', year: '1st Year' },
    { id: '2025-058', name: 'CABANGAL, JOHN VINCENT CABILA', course: 'BA Philo', year: '1st Year' },
    { id: '2025-088', name: 'CABILAO, SHYNA AMOR DAPITO', course: 'BSCE', year: '1st Year' },
    { id: '2025-102', name: 'CABILO, JAMAICA KABAGANI', course: 'BSEd', year: '1st Year' },
    { id: '2025-086', name: 'CABILO, NARISSA KABAGANI', course: 'BSCE', year: '1st Year' },
    { id: '2025-225', name: 'CABURATAN, KISSEAH VYNE CAÑADILLA', course: 'BSCE', year: '1st Year' },
    { id: '2025-060', name: 'CACHUELA, LIZTER JAMES DAGOOC', course: 'BA Philo', year: '1st Year' },
    { id: '2025-182', name: 'CADABONA, AVREN', course: 'BA PoS', year: '1st Year' },
    { id: '2025-231', name: 'CADIZ, RAINER JOSH LUGATIMAN', course: 'BPEd', year: '1st Year' },
    { id: '2025-025', name: 'CALIXTRO, IVAN RITCHIE CRASQUIT', course: 'BA PoS', year: '1st Year' },
    { id: '2025-321', name: 'CALLAMAN, JHONA MEA GILAGA', course: 'BSBA', year: '1st Year' },
    { id: '2025-345', name: 'CAMPO, ALLIYAH JANE DAGOL', course: 'BSN', year: '1st Year' },
    { id: '2025-189', name: 'CAMPOMANES, LAWRENZE ANDREW AJERO', course: 'BA PoS', year: '1st Year' },
    { id: '2025-174', name: 'CANDA, SEAN PRAXIS SOCIAS', course: 'BSIT', year: '1st Year' },
    { id: '2025-210', name: 'CANDELARIO, HANNAH DOROTHY PEDROSO', course: 'BSCE', year: '1st Year' },
    { id: '2025-041', name: 'CANTARONA, CEASAR JOHN JORE', course: 'PROF ED', year: '1st Year' },
    { id: '2025-260', name: 'CARI, JOHN MENARD PADILLA', course: 'BSEcE', year: '1st Year' },
    { id: '2025-131', name: 'CASIMERO, MARYVON NICOLE PIDO', course: 'BSBA', year: '1st Year' },
    { id: '2025-152', name: 'CASINILLO, SHAIRA MAE DALIDA', course: 'BPEd', year: '1st Year' },
    { id: '2025-020', name: 'CASPILLO, RAECEE KEAH SIMBRON', course: 'BSN', year: '1st Year' },
    { id: '2025-365', name: 'CASTILLO, JOHN BERNARD PEÑARANDA', course: 'PROF ED', year: '1st Year' },
    { id: '2025-290', name: 'CATALUÑA, JORELLS JEPH ESPARAGOZA', course: 'BSIT', year: '1st Year' },
    { id: '2025-192', name: 'CATERIO, CYRIL JAY ESPINOSA', course: 'BSEcE', year: '1st Year' },
    { id: '2025-128', name: 'CEDEÑO, JAMELA JOY QUINANAHAN', course: 'BSN', year: '1st Year' },
    { id: '2025-031', name: 'CELORIO, ROMELISA PALMA', course: 'BSEd', year: '1st Year' },
    { id: '2025-026', name: 'CERCADO, KRISTAL JOY SALVALOZA', course: 'BSCE', year: '1st Year' },
    { id: '2025-164', name: 'CLAUD, PRINCE JAY-LON FRANCISCO', course: 'BSBA', year: '1st Year' },
    { id: '2025-043', name: 'CLAVERIA, BENHART KIBANGAN', course: 'BSBA', year: '1st Year' },
    { id: '2024-022', name: 'COLLANTES, KIM JOHN ALVAREZ', course: 'BSN', year: '1st Year' },
    { id: '2024-229', name: 'COMODA, CLAIRE ORTIZ', course: 'BSBA', year: '1st Year' },
    { id: '2025-016', name: 'CONTINEDO, PRINCE JOHN CARL CASINAO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-044', name: 'CORDOVA, HYACINTH CARAGOS', course: 'BPEd', year: '1st Year' },
    { id: '2025-054', name: 'CORPUZ, KYLE ANGELA GEOLINGO', course: 'BSN', year: '1st Year' },
    { id: '2025-002', name: 'CUMAYAS, CHRISTIAN REY DELA CERNA', course: 'BSIT', year: '1st Year' },
    { id: '2025-029', name: 'CUTAD, PRINCES CLAIRE GONZAGA', course: 'BSA', year: '1st Year' },
    { id: '2025-187', name: 'DABUCO, JULS ERICK PERONCE', course: 'BSMA', year: '1st Year' },
    { id: '2025-251', name: 'DACUMOS, JALILA CREST PEPITO', course: 'BSN', year: '1st Year' },
    { id: '2025-279', name: 'DAGUMAN, JOSELE KRIS TANGARA', course: 'BSBA', year: '1st Year' },
    { id: '2025-057', name: 'DAJUELA, RONALD PILLO', course: 'BA Philo', year: '1st Year' },
    { id: '2025-310', name: 'DALUGDOG, ANA MARIE GALVE', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-045', name: 'DANDUAN, CHARLY ANGELES', course: 'BSBA', year: '1st Year' },
    { id: '2025-085', name: 'DANGO, MARICEL BROÑULA', course: 'BSBA', year: '1st Year' },
    { id: '2025-091', name: 'DANO, AECEY CEBALLOS', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-120', name: 'DAQUIPIL, SHERLYN OBTINALLA', course: 'BSA', year: '1st Year' },
    { id: '2025-138', name: 'DAUGDAUG, CHARMEN DUHILAG', course: 'BPEd', year: '1st Year' },
    { id: '2025-046', name: 'DAYONDON, COLLEEN BORGONIA', course: 'BPEd', year: '1st Year' },
    { id: '2025-017', name: 'DAYONDON, PRECIOUS DIANNE DELPOSO', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-087', name: 'DE VIEJO, MARISSA PUROL', course: 'BSBA', year: '1st Year' },
    { id: '2025-336', name: 'DECLARADOR, JANA LEIGHN DAFIELMOTO', course: 'BSN', year: '1st Year' },
    { id: '2025-136', name: 'DEGUIÑON, AXINE ARL HEAVEN BATUCAN', course: 'BPEd', year: '1st Year' },
    { id: '2025-032', name: 'DEL MUNDO, JENYVEB AMENA', course: 'BSBA', year: '1st Year' },
    { id: '2025-039', name: 'DELA CRUZ, ERNEL SUAREZ', course: 'PROF ED', year: '1st Year' },
    { id: '2025-118', name: 'DELA CRUZ, GEORGE GABRIEL DIMAANO', course: 'BSN', year: '1st Year' },
    { id: '2025-144', name: 'DELA CUESTA, KEITH CHRISLER CHATTO', course: 'BPEd', year: '1st Year' },
    { id: '2025-216', name: 'DELFIN, BIANCA JOLYN TION', course: 'BSCE', year: '1st Year' },
    { id: '2021-389', name: 'DELIMA, RIZZA MAE ROLA', course: 'BA Comm', year: '1st Year' },
    { id: '2025-221', name: 'DELINO, JOHN TERRENCE ZAMBRA', course: 'BSBA', year: '1st Year' },
    { id: '2025-322', name: 'DELOS REYES, HANNAH JULIAN SEVILA', course: 'BSBA', year: '1st Year' },
    { id: '2025-298', name: 'DICDIQUIN, LENY NIM', course: 'BSMA', year: '1st Year' },
    { id: '2025-024', name: 'DIEZ, KATHERINE OMANDAC', course: 'BSCE', year: '1st Year' },
    { id: '2025-285', name: 'DIMAANO, DAN JENSEN RAMIREZ', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-166', name: 'DIVINAGRACIA, LEZYLLE MAE DONASCO', course: 'BSA', year: '1st Year' },
    { id: '2025-006', name: 'DOCTOR, ANIKA LORAINE SOLEDAD', course: 'BSMA', year: '1st Year' },
    { id: '2025-034', name: 'DOMINGO, LADY JANE WAGAS', course: 'BSA', year: '1st Year' },
    { id: '2025-282', name: 'DORILAG, ASHTON ALFARAS', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-259', name: 'DOYO, KEITH BYRON FABELLO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-350', name: 'DULAY, BON PATRICK SAPUL', course: 'BSCE', year: '1st Year' },
    { id: '2025-347', name: 'EDRIS, AINOLHAYA SULTAN', course: 'BSN', year: '1st Year' },
    { id: '2025-295', name: 'EDUAVE, JOSHUA CADENAS', course: 'BEEd', year: '1st Year' },
    { id: '2025-073', name: 'ESCALANTE, GEHANNAH ROSE MAULANA', course: 'BSIT', year: '1st Year' },
    { id: '2025-270', name: 'ESCOPALAO, KESHIA ESPAÑOLA', course: 'BSBA', year: '1st Year' },
    { id: '2025-042', name: 'ESPINOSA, LADY JESSICA DEMERIN', course: 'BSIT', year: '1st Year' },
    { id: '2025-364', name: 'ESTRERA, KHIZZ DIANE BANDIOLA', course: 'PROF ED', year: '1st Year' },
    { id: '2025-104', name: 'EXCONDE, AYANNA AXEL BRAGAIS', course: 'BSMA', year: '1st Year' },
    { id: '2025-264', name: 'FABRO, JAIRUS MARCELINO', course: 'BSIT', year: '1st Year' },
    { id: '2025-127', name: 'FALCIS, ASHLEY RESMA', course: 'BSCE', year: '1st Year' },
    { id: '2025-213', name: 'FAMISAN, NATHANIEL ASIS', course: 'PROF ED', year: '1st Year' },
    { id: '2025-077', name: 'FERENAL, JOSHUA BARSAGA', course: 'BSBA', year: '1st Year' },
    { id: '2025-313', name: 'FERNANDEZ, KIRK LOUIE CARAS', course: 'BSEcE', year: '1st Year' },
    { id: '2025-297', name: 'FERRER, JOHN RICK SANGILAN', course: 'BSA', year: '1st Year' },
    { id: '2025-296', name: 'FIGUEROA, KRISTINE MAY MIZON', course: 'BA PoS', year: '1st Year' },
    { id: '2025-149', name: 'FLORES, PRECIOUS JEAMELLA EVANGELISTA', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-309', name: 'FLORITA, JACIENTH CLAIRE PERFAS', course: 'BSMA', year: '1st Year' },
    { id: '2025-083', name: 'FORTUNA, GIAN CARLO DELPOSO', course: 'BSBA', year: '1st Year' },
    { id: '2025-292', name: 'FORTUNA, JENNY ROSE DELPOSO', course: 'BPEd', year: '1st Year' },
    { id: '2025-082', name: 'FRANCO, FEL LYZA NAMOCATCAT', course: 'BSA', year: '1st Year' },
    { id: '2025-108', name: 'GAJES, JANIEL SAMILLANO', course: 'BSCE', year: '1st Year' },
    { id: '2025-330', name: 'GALIZA, REA JANE PANES', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-262', name: 'GANIA, CARLO DANTE SAMAL', course: 'BSCE', year: '1st Year' },
    { id: '2025-134', name: 'GARCIA, XAMUEL XYREN REI CORPUZ', course: 'BA PoS', year: '1st Year' },
    { id: '2025-159', name: 'GAURAN, ANDREY ORIGEN', course: 'BA Philo', year: '1st Year' },
    { id: '2025-349', name: 'GIDO, ALYSSA CLAIRE SINCERO', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-049', name: 'GILACAN, JARL M ARNOLD JIMENA', course: 'BSN', year: '1st Year' },
    { id: '2025-176', name: 'GILBERO, JULIE PEARL PAQUIT', course: 'BSBA', year: '1st Year' },
    { id: '2025-170', name: 'GISON, PIONAH ELLAINE VILLEGAS', course: 'BSCE', year: '1st Year' },
    { id: '2025-114', name: 'GO, MIKEL JEFF BAYLON', course: 'BSCE', year: '1st Year' },
    { id: '2025-033', name: 'GOMEZ, LEO ANTHONY LOCARIO', course: 'BSCE', year: '1st Year' },
    { id: '2025-348', name: 'GRACIA, JANE JELIE DAPAL', course: 'PROF ED', year: '1st Year' },
    { id: '2025-291', name: 'GREGORIO, ALEXA VELARDE', course: 'BSA', year: '1st Year' },
    { id: '2025-198', name: 'GRIÑO, WINSTON YLMAR TAMAYOR', course: 'PROF ED', year: '1st Year' },
    { id: '2025-132', name: 'GUBAT, JUN VINCENT TUMBALOY', course: 'BA Comm', year: '1st Year' },
    { id: '2025-316', name: 'GUBATON, JERIAN SARINO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-248', name: 'GUCOR, BRIAN JAMES TABILO', course: 'BSIT', year: '1st Year' },
    { id: '2025-148', name: 'GUEVARRA, JOIE ELLAINE GAPUZ', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-095', name: 'HADJI RACMAN, HANIMA DIMA', course: 'BSN', year: '1st Year' },
    { id: '2025-244', name: 'HERIDA, SYRELL BARAWIDAN', course: 'BSIT', year: '1st Year' },
    { id: '2025-168', name: 'HERNAN, MARY CHIARA EXCHAURE', course: 'BSBA', year: '1st Year' },
    { id: '2025-340', name: 'HERNANDEZ, NOLYRAINE KRYZEL CAMPAÑA', course: 'BSA', year: '1st Year' },
    { id: '2025-362', name: 'HEYRES, JAMAICA MAE ARCENAL', course: 'BSCE', year: '1st Year' },
    { id: '2025-303', name: 'HORDISTA, MARIA FE SABAS', course: 'BSBA', year: '1st Year' },
    { id: '2025-337', name: 'INECIAL, ANGEL FAITH CENCIA', course: 'BA PoS', year: '1st Year' },
    { id: '2025-332', name: 'INECIAL, CHRISTIAN DOMINIC CENCIA', course: 'BSCE', year: '1st Year' },
    { id: '2025-265', name: 'JAMIL, MOJAINOR DIMAPORO', course: 'BSCE', year: '1st Year' },
    { id: '2025-344', name: 'JORIDICO, JAHN ALBERT TE', course: 'BSCE', year: '1st Year' },
    { id: '2025-155', name: 'JUMAO-AS, ALLYSSA KRIZETTE PALCA', course: 'BSA', year: '1st Year' },
    { id: '2025-172', name: 'JUNTARCIEGO, ANGELA TRESHA LAUREN', course: 'BSBA', year: '1st Year' },
    { id: '2025-171', name: 'JURIAL, PHOEBE JOY ARISTON', course: 'BSA', year: '1st Year' },
    { id: '2025-240', name: 'KINGCO, FRANCIS JADE COYOCA', course: 'BA PoS', year: '1st Year' },
    { id: '2025-130', name: 'LABONETE, THRIXIA BRIANNE JEEZE BALDEMORO', course: 'BSCE', year: '1st Year' },
    { id: '2025-266', name: 'LAMAY, MARIA TRISHA VALERIE DECASA', course: 'BSN', year: '1st Year' },
    { id: '2025-311', name: 'LAMPAYAN, NICOLE JULLIEZA', course: 'BSBA', year: '1st Year' },
    { id: '2025-188', name: 'LANGOMES, CHRISTIAN LIBRE', course: 'BA PoS', year: '1st Year' },
    { id: '2025-048', name: 'LAPUZ, DEEANNE RYZEL PARCON', course: 'BSN', year: '1st Year' },
    { id: '2025-267', name: 'LATO, SHANIAH ROSE MAE ARCIPE', course: 'BSN', year: '1st Year' },
    { id: '2025-201', name: 'LAURON, GEZER KENT TAN', course: 'PROF ED', year: '1st Year' },
    { id: '2025-023', name: 'LIBLORA, OLYN CASPILLO', course: 'BSCE', year: '1st Year' },
    { id: '2024-258', name: 'LIMA, LOIDJIE CELESTIAL', course: 'BSBA', year: '1st Year' },
    { id: '2025-067', name: 'LOSIS, ADRIAN JOHN APURADO', course: 'BSN', year: '1st Year' },
    { id: '2025-037', name: 'LUCERO, DION CLAYTON EBARLE', course: 'BSBA', year: '1st Year' },
    { id: '2025-249', name: 'LUMACAD, GLAIZA PHIERL MARTINEZ', course: 'BSIT', year: '1st Year' },
    { id: '2025-339', name: 'LUMOGDANG, LHEA LANITON', course: 'BSA', year: '1st Year' },
    { id: '2024-215', name: 'LUZON, KIEFER ERIC C', course: 'BSBA', year: '1st Year' },
    { id: '2025-115', name: 'MADIAM, ALEXA SERVANO', course: 'BSA', year: '1st Year' },
    { id: '2025-217', name: 'MAGCALAYO, FELIX DANIEL DURAN', course: 'BSIT', year: '1st Year' },
    { id: '2025-308', name: 'MAGDATO, JOHN KEVIN', course: 'BPEd', year: '1st Year' },
    { id: '2025-273', name: 'MALINGCO, HAYDEE KRISNA SAMAL', course: 'BSCE', year: '1st Year' },
    { id: '2025-324', name: 'MAMAYOG, NYSRHEEN CASULOCAN', course: 'BSA', year: '1st Year' },
    { id: '2025-147', name: 'MAMBURAO, JEAMEL HEART OBAÑA', course: 'BSN', year: '1st Year' },
    { id: '2025-352', name: 'MAMON, VONN KLYDE PUSTA', course: 'PROF ED', year: '1st Year' },
    { id: '2025-268', name: 'MANANSALA, ALLYSSON ANABIEZA', course: 'BSEd', year: '1st Year' },
    { id: '2025-287', name: 'MANLUNAS, NOAH JAY ELTAGON', course: 'BSEcE', year: '1st Year' },
    { id: '2025-224', name: 'MANTULING, NASRAH PENDATUN', course: 'BSBA', year: '1st Year' },
    { id: '2025-356', name: 'MAPA, JUDE MICHAEL MAINIT', course: 'BSCE', year: '1st Year' },
    { id: '2025-190', name: 'MAPANAO, VINCE YUAN COLLADO', course: 'BSCE', year: '1st Year' },
    { id: '2025-084', name: 'MAPUTI, KIEZAH GAIL GLIMADA', course: 'BSBA', year: '1st Year' },
    { id: '2025-359', name: 'MARAGANA, JUSTIN PHILIP NOBLE', course: 'PROF ED', year: '1st Year' },
    { id: '2025-191', name: 'MARFE, JETRO JADE SOBREO', course: 'BPEd', year: '1st Year' },
    { id: '2025-092', name: 'MARQUEZ, GREMAN JANOFER LAPAZ', course: 'BSIT', year: '1st Year' },
    { id: '2025-286', name: 'MEJORADA, JOHN REVO AHIT', course: 'BSIT', year: '1st Year' },
    { id: '2025-293', name: 'MEJORADA, MARK RAVEN AHIT', course: 'BSBA', year: '1st Year' },
    { id: '2025-179', name: 'MENDEZ, REIL ANTHONY ANJAO', course: 'BSIT', year: '1st Year' },
    { id: '2025-253', name: 'MENDOZA, JOHN DOMINIC LEGASPI', course: 'BSN', year: '1st Year' },
    { id: '2025-366', name: 'MENTANG, ALMIRA ANGKAD', course: 'PROF ED', year: '1st Year' },
    { id: '2025-089', name: 'MERIN, LE JOSIAS MADRIO', course: 'BSCE', year: '1st Year' },
    { id: '2024-367', name: 'MILLOMEDA, JOHN LESTER RENDAJE', course: 'BSCE', year: '1st Year' },
    { id: '2025-294', name: 'MOJER, DAEVONE CAMPANO', course: 'BSBA', year: '1st Year' },
    { id: '2025-137', name: 'MONSERATE, NIÑA CHARISSE CUBERO', course: 'BSA', year: '1st Year' },
    { id: '2025-135', name: 'MONTECILLO, ANJELYN DELIMA', course: 'BSA', year: '1st Year' },
    { id: '2025-272', name: 'MONTERO, PRECIOUS KEYANN AARON', course: 'BSBA', year: '1st Year' },
    { id: '2025-254', name: 'MONTEROSO, WELTHON GIEM SALANDANAN', course: 'BSN', year: '1st Year' },
    { id: '2025-047', name: 'MORAN, ARVIN JOY CALUNOD', course: 'BSA', year: '1st Year' },
    { id: '2025-327', name: 'MORANTA, WINZEL LOUISSE GABRIELL RIBUYAS', course: 'BSA', year: '1st Year' },
    { id: '2025-367', name: 'MULAT, RAIZA MIRAFUENTES', course: 'PROF ED', year: '1st Year' },
    { id: '2025-030', name: 'MUSTAPHA, JEOMAR ALIUDIN', course: 'BPEd', year: '1st Year' },
    { id: '2025-110', name: 'NADNADEN, CARL JOSHUA JANOYAN', course: 'BSCE', year: '1st Year' },
    { id: '2025-133', name: 'NADONG, IAN FEL ALOY', course: 'BSCE', year: '1st Year' },
    { id: '2025-269', name: 'NAMIA, ALYAHNNA CZARRHYNE MANSUELO', course: 'BSBA', year: '1st Year' },
    { id: '2025-146', name: 'NAPUTO, ROMEO EDEJER', course: 'BPEd', year: '1st Year' },
    { id: '2025-177', name: 'NARCISO, NICOMEO REGIS', course: 'BSEd', year: '1st Year' },
    { id: '2025-329', name: 'NGAMOY, RAZHI SHANE BARRIENTOS', course: 'BSCE', year: '1st Year' },
    { id: '2025-169', name: 'NICOLAS, PRECIOUS FAITH LOPEZ', course: 'BSA', year: '1st Year' },
    { id: '2024-365', name: 'NOLAN, BRENT KELLY ABELLANOSA', course: 'BSIT', year: '1st Year' },
    { id: '2025-003', name: 'OBEÑA, ENRICK JACINTO', course: 'PROF ED', year: '1st Year' },
    { id: '2025-112', name: 'OCTAVIO, BEA CAMBEL', course: 'BSEd', year: '1st Year' },
    { id: '2025-163', name: 'OLIVEROS, CARL VINCENT JUMAWID', course: 'BSCE', year: '1st Year' },
    { id: '2024-044', name: 'OMANDAC, BETHSHEVA COLOMER', course: 'BEEd', year: '1st Year' },
    { id: '2025-162', name: 'OMANDAM, KERR KLOYD ZEDRIC ROCOLAN', course: 'BSIT', year: '1st Year' },
    { id: '2025-069', name: 'OMBROSA, MICHELLE LYN PACOT', course: 'BSBA', year: '1st Year' },
    { id: '2025-121', name: 'OPENDO, ANDREA MAE CADUNGON', course: 'BSA', year: '1st Year' },
    { id: '2025-119', name: 'ORBE, JANNA NICOLE AMERILA', course: 'BSN', year: '1st Year' },
    { id: '2025-126', name: 'OREGILA, AZALEAH MONTALVA', course: 'BSN', year: '1st Year' },
    { id: '2025-116', name: 'OREIRO, AJELENE BALOS', course: 'BSCE', year: '1st Year' },
    { id: '2025-178', name: 'OTON, ERRON KENT V.J CATALAN', course: 'BSIT', year: '1st Year' },
    { id: '2025-223', name: 'PACETE, MA. EDDESSA RAMOS', course: 'BSN', year: '1st Year' },
    { id: '2025-202', name: 'PADAWAN, JUNIEL QUIM HINAYON', course: 'BSCE', year: '1st Year' },
    { id: '2025-103', name: 'PALERMO, CYRIL KAYE VIDAD', course: 'BSBA', year: '1st Year' },
    { id: '2025-028', name: 'PALIJADO, JOHN ROWIN', course: 'BSCE', year: '1st Year' },
    { id: '2025-014', name: 'PANDIA, ALLYAN NAVARRO', course: 'BSCE', year: '1st Year' },
    { id: '2025-141', name: 'PANDONG, MERRY CHRIST MANTAWIL', course: 'PROF ED', year: '1st Year' },
    { id: '2025-094', name: 'PAPASIN, LEIGHANN DIEZON', course: 'BSN', year: '1st Year' },
    { id: '2025-099', name: 'PARDILLO, JOCEL PELORIANA', course: 'BSA', year: '1st Year' },
    { id: '2025-107', name: 'PAREÑAS, LORRAINE SARTE', course: 'BSN', year: '1st Year' },
    { id: '2025-175', name: 'PASTORIL, CHARLES BENEDICT TUMANGGONG', course: 'BSCE', year: '1st Year' },
    { id: '2025-027', name: 'PATAC, GARY ABO-ABO', course: 'BSIT', year: '1st Year' },
    { id: '2025-304', name: 'PATCHES, IVY FAYE MAGALLON', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-335', name: 'PENIERO, NATHAN ANIÑON', course: 'BSIT', year: '1st Year' },
    { id: '2025-195', name: 'PERAL, JOHN MARK DEVALID', course: 'PROF ED', year: '1st Year' },
    { id: '2025-325', name: 'PEREYRA, LAURENCE RAMOS', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-204', name: 'PILAPIL, CARL ANDRY BAYA', course: 'BSIT', year: '1st Year' },
    { id: '2025-129', name: 'POLICAR, EDRIAN PERALES', course: 'BSCE', year: '1st Year' },
    { id: '2025-105', name: 'POLINIO, ALMA JANE AGUILAR', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-066', name: 'PORRAS, PAULO EDRIAN CALANDRIA', course: 'BA Philo', year: '1st Year' },
    { id: '2025-070', name: 'PRE, PRINCE ZIELO VERDAN', course: 'BSCE', year: '1st Year' },
    { id: '2025-100', name: 'PUN-AN, JOHN CHRISTIAN TRANCE', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-255', name: 'QUANICO, RONALEN JUAREZ', course: 'BSMA', year: '1st Year' },
    { id: '2025-062', name: 'QUIMCO, KRISTOFFER ESTELLOSO', course: 'BSCE', year: '1st Year' },
    { id: '2024-078', name: 'QUIÑONES, MARIO IV NARCISO', course: 'BSCE', year: '1st Year' },
    { id: '2025-209', name: 'QUIROZ, JAMES JOHN PAUL CANDOLE', course: 'BSCE', year: '1st Year' },
    { id: '2025-302', name: 'RABUYA, CLOUIE TORREON', course: 'BSA', year: '1st Year' },
    { id: '2025-096', name: 'RAHMAN, JOHANIS BERNADAS', course: 'BSIT', year: '1st Year' },
    { id: '2025-237', name: 'RASUL, SITTIE AIMAH SUNGGOD', course: 'BSA', year: '1st Year' },
    { id: '2025-361', name: 'RAYMUNDO, LOVELYN JEAN PACIENTE', course: 'PROF ED', year: '1st Year' },
    { id: '2025-222', name: 'RAZON, THEO ALCONERA', course: 'BSIT', year: '1st Year' },
    { id: '2025-068', name: 'REGUYAL, DANIELLA MAE OCON', course: 'BSBA', year: '1st Year' },
    { id: '2025-355', name: 'RENEGADO, DOVE QUIBEDO', course: 'BSBA', year: '1st Year' },
    { id: '2025-052', name: 'RETIZA, JIRAH JOY LUMOGDANG', course: 'BA Comm', year: '1st Year' },
    { id: '2025-212', name: 'REYES, MAURICE RATILLA', course: 'BPEd', year: '1st Year' },
    { id: '2025-242', name: 'RICALE, PRINCESS CHAREZ PALOMO', course: 'BSA', year: '1st Year' },
    { id: '2025-228', name: 'RIVERA, JUSTINE LLOYD PATRICIO', course: 'BPEd', year: '1st Year' },
    { id: '2025-165', name: 'ROCHE, ADRIAN CARL UNTAL', course: 'BSCE', year: '1st Year' },
    { id: '2025-230', name: 'RONDAEL, TRESHA NICA SURIAGA', course: 'BSEd', year: '1st Year' },
    { id: '2024-353', name: 'ROSARIO, ANGELIKA KATE VERGARA', course: 'BSBA', year: '1st Year' },
    { id: '2025-079', name: 'SACASAN, KYLE CIAN PASCO', course: 'BSA', year: '1st Year' },
    { id: '2025-038', name: 'SAGAYCA, DWYNE MATHEW PEROCHO', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-219', name: 'SALAZAR, CHRISTIAN JOSH ABELLANA', course: 'BSIT', year: '1st Year' },
    { id: '2025-008', name: 'SALGADO, JOHNVER KENT DE VILLA', course: 'BSMA', year: '1st Year' },
    { id: '2025-214', name: 'SALIK, SHAHANIE TALIB', course: 'BSN', year: '1st Year' },
    { id: '2025-111', name: 'SALISE, CARL MARLOU BIÑGIL', course: 'BSCE', year: '1st Year' },
    { id: '2025-256', name: 'SALMORIN, ALFRED R-JAY GULMATICO', course: 'BSN', year: '1st Year' },
    { id: '2025-113', name: 'SALVALOZA, CHARLES JADE EVANGELISTA', course: 'BSCE', year: '1st Year' },
    { id: '2025-353', name: 'SAMATULA, JOHARISA NAYAN', course: 'BSBA', year: '1st Year' },
    { id: '2025-343', name: 'SANCHEZ, ERIC BYRON JAVIER', course: 'BSBA', year: '1st Year' },
    { id: '2025-363', name: 'SANTOS, FRANZEL KAYE ASOTIGUE', course: 'PROF ED', year: '1st Year' },
    { id: '2025-061', name: 'SARA, AARON CAESAR EVANGELIO', course: 'BA Philo', year: '1st Year' },
    { id: '2025-050', name: 'SARAPODIN, JAMELA FAWZIA GRIÑO', course: 'BSN', year: '1st Year' },
    { id: '2025-258', name: 'SARIOL, DANIELLA CASAYAS', course: 'BSCE', year: '1st Year' },
    { id: '2025-018', name: 'SEDORIOSA, JAYLOU BANTES', course: 'BSCE', year: '1st Year' },
    { id: '2025-238', name: 'SERAFINO, KASHIECA', course: 'BSA', year: '1st Year' },
    { id: '2025-078', name: 'SERAG, JILLIANE CUA', course: 'BSN', year: '1st Year' },
    { id: '2025-080', name: 'SERRANO, URIEL TADOR', course: 'BA PoS', year: '1st Year' },
    { id: '2025-196', name: 'SIATOCA, DONALYN CARBON', course: 'PROF ED', year: '1st Year' },
    { id: '2025-040', name: 'SIBUGAN, DIVINE JAMAICA SUDARIO', course: 'BEEd', year: '1st Year' },
    { id: '2025-090', name: 'SICADA, YVETTE VILLAGOMEZ', course: 'BSMA', year: '1st Year' },
    { id: '2025-206', name: 'SILADAN, GIVE ARTHOR AQUINO', course: 'BSN', year: '1st Year' },
    { id: '2025-274', name: 'SILVA, ALYSSA GIRAO', course: 'BSN', year: '1st Year' },
    { id: '2025-156', name: 'SILVESTRE, FEA DASIG', course: 'BSA', year: '1st Year' },
    { id: '2025-055', name: 'SIMBAJON, BRISSA MASENDO', course: 'BSA', year: '1st Year' },
    { id: '2025-211', name: 'SIMBAJON, JERRY FLORES', course: 'BSN', year: '1st Year' },
    { id: '2025-142', name: 'SITONES, MEAH DIANNE MIRASOL', course: 'BSEd', year: '1st Year' },
    { id: '2025-075', name: 'SOJOR, DAREN MAE SALUT', course: 'BA PoS', year: '1st Year' },
    { id: '2024-355', name: 'SOLATORIO, JUVE FRIEL AGRAVIADOR', course: 'BSBA', year: '1st Year' },
    { id: '2025-284', name: 'SOMBLINGO, CRISTIAN CHAD CORDERO', course: 'BSEcE', year: '1st Year' },
    { id: '2025-257', name: 'SORIANO, ALEC DANE PAREÑAS', course: 'BSEcE', year: '1st Year' },
    { id: '2025-101', name: 'SORIANO, MICAH CRISELLE FAITH ASUTILLA', course: 'BSA', year: '1st Year' },
    { id: '2025-035', name: 'STA. CRUZ, JASMINE ARTISTA', course: 'BSBA', year: '1st Year' },
    { id: '2025-318', name: 'SULIGUIN, EFREN RELANADO', course: 'BSBA', year: '1st Year' },
    { id: '2025-021', name: 'SUMAGIT, MICO LUAYON', course: 'BSN', year: '1st Year' },
    { id: '2025-064', name: 'SUPNET, FRANCIS JOHN BAYON', course: 'BA Philo', year: '1st Year' },
    { id: '2025-261', name: 'TAAS, KYLA SHANE REYNO', course: 'BSCE', year: '1st Year' },
    { id: '2025-007', name: 'TABILLA, NICOLE TOLENTINO', course: 'BSBA', year: '1st Year' },
    { id: '2022-213', name: 'TABORA, KURT FRANCIS FLORESTA', course: 'BSIT', year: '1st Year' },
    { id: '2025-229', name: 'TAJOLOSA, DONNA BELLE TAMONAN', course: 'BS Psychology', year: '1st Year' },
    { id: '2025-194', name: 'TALAVER, YASMEN GWYNETH BUGTAY', course: 'BSBA', year: '1st Year' },
    { id: '2025-243', name: 'TAMPOY, CHLOE JANE UMPAD', course: 'BSBA', year: '1st Year' },
    { id: '2025-076', name: 'TANAKA, SAKURA VILLANUEVA', course: 'BSCE', year: '1st Year' },
    { id: '2025-063', name: 'TANALGO, YSRAEL ANTONIO LANCE', course: 'BSCE', year: '1st Year' },
    { id: '2025-167', name: 'TAYAPAD, CEDRIC JAMES DUREMDES', course: 'BSIT', year: '1st Year' },
    { id: '2025-185', name: 'TEQUIN, JUSTINE LEI VILLOGA', course: 'BSCE', year: '1st Year' },
    { id: '2025-299', name: 'TORANEO, LAURENCE ABANTES', course: 'BSCE', year: '1st Year' },
    { id: '2025-125', name: 'TORITA, JOHN MARLOU MOJAL', course: 'BPEd', year: '1st Year' },
    { id: '2025-351', name: 'TUBURAN, JET RHO BOLORON', course: 'BSCE', year: '1st Year' },
    { id: '2025-288', name: 'TUYOR, LUIS ADRIAN ARAMBALA', course: 'BSCE', year: '1st Year' },
    { id: '2025-317', name: 'UDA, VIRGILIO ALBINO', course: 'BSBA', year: '1st Year' },
    { id: '2025-226', name: 'UMALI, SHAYNE FRANCIS SINGCO', course: 'BPEd', year: '1st Year' },
    { id: '2025-160', name: 'UNABIA, CLENT JOHNCEL SINGCO', course: 'BSIT', year: '1st Year' },
    { id: '2025-220', name: 'VALENCIA, EDIZ FAYE BADILLA', course: 'BSN', year: '1st Year' },
    { id: '2025-276', name: 'VALLES, JIANNE CARLO GAABUCAYAN', course: 'BSN', year: '1st Year' },
    { id: '2025-098', name: 'VELARDE, ANGEL KYLE COLLADO', course: 'BSA', year: '1st Year' },
    { id: '2025-193', name: 'VELARDE, PRINCE KERT BASILAN', course: 'BA Psychology', year: '1st Year' },
    { id: '2025-005', name: 'VELOS, ALLEAH GRACE DOLIDO', course: 'BSA', year: '1st Year' },
    { id: '2025-241', name: 'VERGARA, HYNNRICH', course: 'BSA', year: '1st Year' },
    { id: '2025-117', name: 'VICTORIA, XYREN MAE DOYSABAS', course: 'BSA', year: '1st Year' },
    { id: '2025-199', name: 'VIDAL, ERICA CHRISTEE MAE GONZALES', course: 'PROF ED', year: '1st Year' },
    { id: '2025-059', name: 'VILLALON, ASHER ZACCHARY JADAN', course: 'BA Philo', year: '1st Year' },
    { id: '2025-140', name: 'VILLARUEL, GRACE DARLE', course: 'BSEd', year: '1st Year' },
    { id: '2025-013', name: 'WABINGGA, CHARIES DUA', course: 'BSBA', year: '1st Year' },
    { id: '2025-275', name: 'WEILL, ALEXANDRA THESSA MARIE', course: 'BA PoS', year: '1st Year' },
    { id: '2025-051', name: 'YBAÑEZ, MIA CATALAN', course: 'PROF ED', year: '1st Year' },
    { id: '2025-173', name: 'ZAMORA, RANZ IVAN ESCOPALAO', course: 'BSMA', year: '1st Year' },
    { id: '2025-065', name: 'ZARAGOSA, JIMREX FAJURANO', course: 'BA Philo', year: '1st Year' }
  ];

  const results = {
    total: students.length,
    added: 0,
    skipped: 0,
    errors: 0,
    skippedStudents: [] as string[]
  };

  for (const student of students) {
    try {
      // Check if student already exists by ID
      const existingById = await studentService.findStudentByBarcode(student.id, 'notre-dame');
      
      if (existingById) {
        results.skipped++;
        results.skippedStudents.push(`${student.id} - ${student.name} (student ID already exists)`);
        continue;
      }

      // Check if student already exists by exact name
      const allStudents = await studentService.getStudents();
      const existingByName = allStudents.find(s => 
        s.name.toUpperCase() === student.name.toUpperCase() && 
        s.library === 'notre-dame'
      );
      
      if (existingByName) {
        results.skipped++;
        results.skippedStudents.push(`${student.id} - ${student.name} (duplicate name: already exists as ${existingByName.studentId})`);
        continue;
      }

      // Add student
      await studentService.addStudent({
        name: student.name,
        studentId: student.id,
        course: student.course,
        year: student.year,
        department: getDepartmentFromCourse(student.course),
        userType: 'student',
        studentType: 'college',
        level: 'college',
        library: 'notre-dame'
      });

      results.added++;
      
      // Small delay to avoid overwhelming the system
      await new Promise(resolve => setTimeout(resolve, 10));
      
    } catch (error) {
      console.error(`Error adding ${student.id}:`, error);
      results.errors++;
      results.skippedStudents.push(`${student.id} - ${student.name} (error: ${error})`);
    }
  }

  return results;
};
